/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package observer.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * The category data.
 */
@ApiModel(description = "The category data.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class CategoryDto {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_LEAF = "leaf";
  @SerializedName(SERIALIZED_NAME_LEAF)
  private Boolean leaf;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_OPTIONS = "options";
  @SerializedName(SERIALIZED_NAME_OPTIONS)
  private CategoryOptionsDto options;

  public static final String SERIALIZED_NAME_PARENT = "parent";
  @SerializedName(SERIALIZED_NAME_PARENT)
  private CategoryDtoParent parent;


  public CategoryDto id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The ID of the category. This can be either in UUID format or an integer format. You should be ready to accept any string value as the category ID.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "12", value = "The ID of the category. This can be either in UUID format or an integer format. You should be ready to accept any string value as the category ID.")

  public String getId() {
    return id;
  }



  public void setId(String id) {
    this.id = id;
  }


  public CategoryDto leaf(Boolean leaf) {
    
    this.leaf = leaf;
    return this;
  }

   /**
   * Indicates whether the category is at the lowest level. Leaf categories do not have any children. Offers can be listed only in leaf categories.
   * @return leaf
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates whether the category is at the lowest level. Leaf categories do not have any children. Offers can be listed only in leaf categories.")

  public Boolean getLeaf() {
    return leaf;
  }



  public void setLeaf(Boolean leaf) {
    this.leaf = leaf;
  }


  public CategoryDto name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the category in Polish.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Pozostałe", value = "Name of the category in Polish.")

  public String getName() {
    return name;
  }



  public void setName(String name) {
    this.name = name;
  }


  public CategoryDto options(CategoryOptionsDto options) {
    
    this.options = options;
    return this;
  }

   /**
   * Get options
   * @return options
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CategoryOptionsDto getOptions() {
    return options;
  }



  public void setOptions(CategoryOptionsDto options) {
    this.options = options;
  }


  public CategoryDto parent(CategoryDtoParent parent) {
    
    this.parent = parent;
    return this;
  }

   /**
   * Get parent
   * @return parent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CategoryDtoParent getParent() {
    return parent;
  }



  public void setParent(CategoryDtoParent parent) {
    this.parent = parent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CategoryDto categoryDto = (CategoryDto) o;
    return Objects.equals(this.id, categoryDto.id) &&
        Objects.equals(this.leaf, categoryDto.leaf) &&
        Objects.equals(this.name, categoryDto.name) &&
        Objects.equals(this.options, categoryDto.options) &&
        Objects.equals(this.parent, categoryDto.parent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, leaf, name, options, parent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CategoryDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    leaf: ").append(toIndentedString(leaf)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

