/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package observer.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * Order item
 */
@ApiModel(description = "Order item")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class CheckoutFormLineItem {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_OFFER = "offer";
  @SerializedName(SERIALIZED_NAME_OFFER)
  private OfferReference offer;

  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  private BigDecimal quantity;

  public static final String SERIALIZED_NAME_ORIGINAL_PRICE = "originalPrice";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_PRICE)
  private Price originalPrice;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private Price price;

  public static final String SERIALIZED_NAME_SELECTED_ADDITIONAL_SERVICES = "selectedAdditionalServices";
  @SerializedName(SERIALIZED_NAME_SELECTED_ADDITIONAL_SERVICES)
  private List<CheckoutFormAdditionalService> selectedAdditionalServices = null;

  public static final String SERIALIZED_NAME_BOUGHT_AT = "boughtAt";
  @SerializedName(SERIALIZED_NAME_BOUGHT_AT)
  private OffsetDateTime boughtAt;


  public CheckoutFormLineItem id(UUID id) {
    
    this.id = id;
    return this;
  }

   /**
   * Line item identifier
   * @return id
  **/
  @ApiModelProperty(example = "62ae358b-8f65-4fc4-9c77-bedf604a2e2b", required = true, value = "Line item identifier")

  public UUID getId() {
    return id;
  }



  public void setId(UUID id) {
    this.id = id;
  }


  public CheckoutFormLineItem offer(OfferReference offer) {
    
    this.offer = offer;
    return this;
  }

   /**
   * Get offer
   * @return offer
  **/
  @ApiModelProperty(required = true, value = "")

  public OfferReference getOffer() {
    return offer;
  }



  public void setOffer(OfferReference offer) {
    this.offer = offer;
  }


  public CheckoutFormLineItem quantity(BigDecimal quantity) {
    
    this.quantity = quantity;
    return this;
  }

   /**
   * quantity
   * @return quantity
  **/
  @ApiModelProperty(example = "1", required = true, value = "quantity")

  public BigDecimal getQuantity() {
    return quantity;
  }



  public void setQuantity(BigDecimal quantity) {
    this.quantity = quantity;
  }


  public CheckoutFormLineItem originalPrice(Price originalPrice) {
    
    this.originalPrice = originalPrice;
    return this;
  }

   /**
   * Get originalPrice
   * @return originalPrice
  **/
  @ApiModelProperty(required = true, value = "")

  public Price getOriginalPrice() {
    return originalPrice;
  }



  public void setOriginalPrice(Price originalPrice) {
    this.originalPrice = originalPrice;
  }


  public CheckoutFormLineItem price(Price price) {
    
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @ApiModelProperty(required = true, value = "")

  public Price getPrice() {
    return price;
  }



  public void setPrice(Price price) {
    this.price = price;
  }


  public CheckoutFormLineItem selectedAdditionalServices(List<CheckoutFormAdditionalService> selectedAdditionalServices) {
    
    this.selectedAdditionalServices = selectedAdditionalServices;
    return this;
  }

  public CheckoutFormLineItem addSelectedAdditionalServicesItem(CheckoutFormAdditionalService selectedAdditionalServicesItem) {
    if (this.selectedAdditionalServices == null) {
      this.selectedAdditionalServices = new ArrayList<CheckoutFormAdditionalService>();
    }
    this.selectedAdditionalServices.add(selectedAdditionalServicesItem);
    return this;
  }

   /**
   * Get selectedAdditionalServices
   * @return selectedAdditionalServices
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<CheckoutFormAdditionalService> getSelectedAdditionalServices() {
    return selectedAdditionalServices;
  }



  public void setSelectedAdditionalServices(List<CheckoutFormAdditionalService> selectedAdditionalServices) {
    this.selectedAdditionalServices = selectedAdditionalServices;
  }


  public CheckoutFormLineItem boughtAt(OffsetDateTime boughtAt) {
    
    this.boughtAt = boughtAt;
    return this;
  }

   /**
   * ISO date when offer was bought
   * @return boughtAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ISO date when offer was bought")

  public OffsetDateTime getBoughtAt() {
    return boughtAt;
  }



  public void setBoughtAt(OffsetDateTime boughtAt) {
    this.boughtAt = boughtAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckoutFormLineItem checkoutFormLineItem = (CheckoutFormLineItem) o;
    return Objects.equals(this.id, checkoutFormLineItem.id) &&
        Objects.equals(this.offer, checkoutFormLineItem.offer) &&
        Objects.equals(this.quantity, checkoutFormLineItem.quantity) &&
        Objects.equals(this.originalPrice, checkoutFormLineItem.originalPrice) &&
        Objects.equals(this.price, checkoutFormLineItem.price) &&
        Objects.equals(this.selectedAdditionalServices, checkoutFormLineItem.selectedAdditionalServices) &&
        Objects.equals(this.boughtAt, checkoutFormLineItem.boughtAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, offer, quantity, originalPrice, price, selectedAdditionalServices, boughtAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckoutFormLineItem {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    offer: ").append(toIndentedString(offer)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    originalPrice: ").append(toIndentedString(originalPrice)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    selectedAdditionalServices: ").append(toIndentedString(selectedAdditionalServices)).append("\n");
    sb.append("    boughtAt: ").append(toIndentedString(boughtAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

