/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package observer.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * CheckoutFormInvoiceAddressNaturalPerson
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class CheckoutFormInvoiceAddressNaturalPerson {
  public static final String SERIALIZED_NAME_FIRST_NAME = "firstName";
  @SerializedName(SERIALIZED_NAME_FIRST_NAME)
  private String firstName;

  public static final String SERIALIZED_NAME_LAST_NAME = "lastName";
  @SerializedName(SERIALIZED_NAME_LAST_NAME)
  private String lastName;


  public CheckoutFormInvoiceAddressNaturalPerson firstName(String firstName) {
    
    this.firstName = firstName;
    return this;
  }

   /**
   * Invoice receiver first name
   * @return firstName
  **/
  @ApiModelProperty(example = "Jan", required = true, value = "Invoice receiver first name")

  public String getFirstName() {
    return firstName;
  }



  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }


  public CheckoutFormInvoiceAddressNaturalPerson lastName(String lastName) {
    
    this.lastName = lastName;
    return this;
  }

   /**
   * Invoice receiver last name
   * @return lastName
  **/
  @ApiModelProperty(example = "Kowalski", required = true, value = "Invoice receiver last name")

  public String getLastName() {
    return lastName;
  }



  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckoutFormInvoiceAddressNaturalPerson checkoutFormInvoiceAddressNaturalPerson = (CheckoutFormInvoiceAddressNaturalPerson) o;
    return Objects.equals(this.firstName, checkoutFormInvoiceAddressNaturalPerson.firstName) &&
        Objects.equals(this.lastName, checkoutFormInvoiceAddressNaturalPerson.lastName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstName, lastName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckoutFormInvoiceAddressNaturalPerson {\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

