/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package observer.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * CheckoutFormDeliveryAddress
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class CheckoutFormDeliveryAddress {
  public static final String SERIALIZED_NAME_FIRST_NAME = "firstName";
  @SerializedName(SERIALIZED_NAME_FIRST_NAME)
  private String firstName;

  public static final String SERIALIZED_NAME_LAST_NAME = "lastName";
  @SerializedName(SERIALIZED_NAME_LAST_NAME)
  private String lastName;

  public static final String SERIALIZED_NAME_STREET = "street";
  @SerializedName(SERIALIZED_NAME_STREET)
  private String street;

  public static final String SERIALIZED_NAME_CITY = "city";
  @SerializedName(SERIALIZED_NAME_CITY)
  private String city;

  public static final String SERIALIZED_NAME_ZIP_CODE = "zipCode";
  @SerializedName(SERIALIZED_NAME_ZIP_CODE)
  private String zipCode;

  public static final String SERIALIZED_NAME_COUNTRY_CODE = "countryCode";
  @SerializedName(SERIALIZED_NAME_COUNTRY_CODE)
  private String countryCode;

  public static final String SERIALIZED_NAME_COMPANY_NAME = "companyName";
  @SerializedName(SERIALIZED_NAME_COMPANY_NAME)
  private String companyName;

  public static final String SERIALIZED_NAME_PHONE_NUMBER = "phoneNumber";
  @SerializedName(SERIALIZED_NAME_PHONE_NUMBER)
  private String phoneNumber;


  public CheckoutFormDeliveryAddress firstName(String firstName) {
    
    this.firstName = firstName;
    return this;
  }

   /**
   * Receiver&#39;s first name
   * @return firstName
  **/
  @ApiModelProperty(example = "Jan", required = true, value = "Receiver's first name")

  public String getFirstName() {
    return firstName;
  }



  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }


  public CheckoutFormDeliveryAddress lastName(String lastName) {
    
    this.lastName = lastName;
    return this;
  }

   /**
   * Receiver&#39;s last name
   * @return lastName
  **/
  @ApiModelProperty(example = "Kowalski", required = true, value = "Receiver's last name")

  public String getLastName() {
    return lastName;
  }



  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  public CheckoutFormDeliveryAddress street(String street) {
    
    this.street = street;
    return this;
  }

   /**
   * Street name
   * @return street
  **/
  @ApiModelProperty(example = "Grunwaldzka 182", required = true, value = "Street name")

  public String getStreet() {
    return street;
  }



  public void setStreet(String street) {
    this.street = street;
  }


  public CheckoutFormDeliveryAddress city(String city) {
    
    this.city = city;
    return this;
  }

   /**
   * City name
   * @return city
  **/
  @ApiModelProperty(example = "Poznań", required = true, value = "City name")

  public String getCity() {
    return city;
  }



  public void setCity(String city) {
    this.city = city;
  }


  public CheckoutFormDeliveryAddress zipCode(String zipCode) {
    
    this.zipCode = zipCode;
    return this;
  }

   /**
   * Postal code
   * @return zipCode
  **/
  @ApiModelProperty(example = "60-166", required = true, value = "Postal code")

  public String getZipCode() {
    return zipCode;
  }



  public void setZipCode(String zipCode) {
    this.zipCode = zipCode;
  }


  public CheckoutFormDeliveryAddress countryCode(String countryCode) {
    
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Country code
   * @return countryCode
  **/
  @ApiModelProperty(example = "PL", required = true, value = "Country code")

  public String getCountryCode() {
    return countryCode;
  }



  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }


  public CheckoutFormDeliveryAddress companyName(String companyName) {
    
    this.companyName = companyName;
    return this;
  }

   /**
   * Company name
   * @return companyName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Company name")

  public String getCompanyName() {
    return companyName;
  }



  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }


  public CheckoutFormDeliveryAddress phoneNumber(String phoneNumber) {
    
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Phone number
   * @return phoneNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Phone number")

  public String getPhoneNumber() {
    return phoneNumber;
  }



  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckoutFormDeliveryAddress checkoutFormDeliveryAddress = (CheckoutFormDeliveryAddress) o;
    return Objects.equals(this.firstName, checkoutFormDeliveryAddress.firstName) &&
        Objects.equals(this.lastName, checkoutFormDeliveryAddress.lastName) &&
        Objects.equals(this.street, checkoutFormDeliveryAddress.street) &&
        Objects.equals(this.city, checkoutFormDeliveryAddress.city) &&
        Objects.equals(this.zipCode, checkoutFormDeliveryAddress.zipCode) &&
        Objects.equals(this.countryCode, checkoutFormDeliveryAddress.countryCode) &&
        Objects.equals(this.companyName, checkoutFormDeliveryAddress.companyName) &&
        Objects.equals(this.phoneNumber, checkoutFormDeliveryAddress.phoneNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstName, lastName, street, city, zipCode, countryCode, companyName, phoneNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckoutFormDeliveryAddress {\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    zipCode: ").append(toIndentedString(zipCode)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

