/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package observer.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Status of single command task.
 */
@ApiModel(description = "Status of single command task.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class CommandTask {
  public static final String SERIALIZED_NAME_FIELD = "field";
  @SerializedName(SERIALIZED_NAME_FIELD)
  private String field;

  public static final String SERIALIZED_NAME_FINISHED_AT = "finishedAt";
  @SerializedName(SERIALIZED_NAME_FINISHED_AT)
  private OffsetDateTime finishedAt;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_OFFER = "offer";
  @SerializedName(SERIALIZED_NAME_OFFER)
  private OfferId offer;

  public static final String SERIALIZED_NAME_SCHEDULED_AT = "scheduledAt";
  @SerializedName(SERIALIZED_NAME_SCHEDULED_AT)
  private OffsetDateTime scheduledAt;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_ERRORS = "errors";
  @SerializedName(SERIALIZED_NAME_ERRORS)
  private List<Error> errors = null;


  public CommandTask field(String field) {
    
    this.field = field;
    return this;
  }

   /**
   * Modified field as JSON path.
   * @return field
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Modified field as JSON path.")

  public String getField() {
    return field;
  }



  public void setField(String field) {
    this.field = field;
  }


  public CommandTask finishedAt(OffsetDateTime finishedAt) {
    
    this.finishedAt = finishedAt;
    return this;
  }

   /**
   * Date of completion of the modification. Format (ISO 8601) - yyyy-MM-dd&#39;T&#39;HH:mm:ss.SSSZ
   * @return finishedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date of completion of the modification. Format (ISO 8601) - yyyy-MM-dd'T'HH:mm:ss.SSSZ")

  public OffsetDateTime getFinishedAt() {
    return finishedAt;
  }



  public void setFinishedAt(OffsetDateTime finishedAt) {
    this.finishedAt = finishedAt;
  }


  public CommandTask message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * General fail reason. You should check the errors structure to get more detailed information of the encountered errors.
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "General fail reason. You should check the errors structure to get more detailed information of the encountered errors.")

  public String getMessage() {
    return message;
  }



  public void setMessage(String message) {
    this.message = message;
  }


  public CommandTask offer(OfferId offer) {
    
    this.offer = offer;
    return this;
  }

   /**
   * Get offer
   * @return offer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OfferId getOffer() {
    return offer;
  }



  public void setOffer(OfferId offer) {
    this.offer = offer;
  }


  public CommandTask scheduledAt(OffsetDateTime scheduledAt) {
    
    this.scheduledAt = scheduledAt;
    return this;
  }

   /**
   * Date of the modification schedule. Format (ISO 8601) - yyyy-MM-dd&#39;T&#39;HH:mm:ss.SSSZ
   * @return scheduledAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date of the modification schedule. Format (ISO 8601) - yyyy-MM-dd'T'HH:mm:ss.SSSZ")

  public OffsetDateTime getScheduledAt() {
    return scheduledAt;
  }



  public void setScheduledAt(OffsetDateTime scheduledAt) {
    this.scheduledAt = scheduledAt;
  }


  public CommandTask status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Available statuses: NEW, SUCCESS, FAIL
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Available statuses: NEW, SUCCESS, FAIL")

  public String getStatus() {
    return status;
  }



  public void setStatus(String status) {
    this.status = status;
  }


  public CommandTask errors(List<Error> errors) {
    
    this.errors = errors;
    return this;
  }

  public CommandTask addErrorsItem(Error errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<Error>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * The list of error objects explaining the problems with command processing for the given offer.
   * @return errors
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The list of error objects explaining the problems with command processing for the given offer.")

  public List<Error> getErrors() {
    return errors;
  }



  public void setErrors(List<Error> errors) {
    this.errors = errors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommandTask commandTask = (CommandTask) o;
    return Objects.equals(this.field, commandTask.field) &&
        Objects.equals(this.finishedAt, commandTask.finishedAt) &&
        Objects.equals(this.message, commandTask.message) &&
        Objects.equals(this.offer, commandTask.offer) &&
        Objects.equals(this.scheduledAt, commandTask.scheduledAt) &&
        Objects.equals(this.status, commandTask.status) &&
        Objects.equals(this.errors, commandTask.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(field, finishedAt, message, offer, scheduledAt, status, errors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommandTask {\n");
    sb.append("    field: ").append(toIndentedString(field)).append("\n");
    sb.append("    finishedAt: ").append(toIndentedString(finishedAt)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    offer: ").append(toIndentedString(offer)).append("\n");
    sb.append("    scheduledAt: ").append(toIndentedString(scheduledAt)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

