/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package observer.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * CompatibleProductsListDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class CompatibleProductsListDto {
  public static final String SERIALIZED_NAME_COMPATIBLE_PRODUCTS = "compatibleProducts";
  @SerializedName(SERIALIZED_NAME_COMPATIBLE_PRODUCTS)
  private List<CompatibleProductDto> compatibleProducts = null;

  public static final String SERIALIZED_NAME_COUNT = "count";
  @SerializedName(SERIALIZED_NAME_COUNT)
  private Integer count;

  public static final String SERIALIZED_NAME_TOTAL_COUNT = "totalCount";
  @SerializedName(SERIALIZED_NAME_TOTAL_COUNT)
  private Integer totalCount;


  public CompatibleProductsListDto compatibleProducts(List<CompatibleProductDto> compatibleProducts) {
    
    this.compatibleProducts = compatibleProducts;
    return this;
  }

  public CompatibleProductsListDto addCompatibleProductsItem(CompatibleProductDto compatibleProductsItem) {
    if (this.compatibleProducts == null) {
      this.compatibleProducts = new ArrayList<CompatibleProductDto>();
    }
    this.compatibleProducts.add(compatibleProductsItem);
    return this;
  }

   /**
   * List of compatible products for given type and parameters.
   * @return compatibleProducts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[{\"id\":\"fc1058e6-a901-4b58-be4d-3d7e1368f63e\",\"text\":\"AUDI A6 (4G2, 4GC, C7) 2014/09-2018/09 3.0 TDI quattro 326KM/240kW\",\"group\":{\"id\":\"19d71c872aa6c78663876a7e7bc7776d\"},\"attributes\":[{\"id\":\"POWER_KW\",\"values\":[\"240\"]},{\"id\":\"MODEL_FROM\",\"values\":[\"2010/11\"]},{\"id\":\"BRAND\",\"values\":[\"AUDI\"]},{\"id\":\"POWER_HP\",\"values\":[\"326\"]},{\"id\":\"MODEL_TO\",\"values\":[\"2018/09\"]},{\"id\":\"ENGINE_CODE\",\"values\":[\"CVUB\"]},{\"id\":\"K_TYP_NR\",\"values\":[\"108441\"]},{\"id\":\"VERSION_FROM\",\"values\":[\"2014/09\"]},{\"id\":\"VERSION_TO\",\"values\":[\"2018/09\"]},{\"id\":\"MODEL\",\"values\":[\"A6 (4G2, 4GC, C7)\"]},{\"id\":\"BODY\",\"values\":[\"sedan\"]},{\"id\":\"TYPE\",\"values\":[\"3.0 TDI quattro\"]}]}]", value = "List of compatible products for given type and parameters.")

  public List<CompatibleProductDto> getCompatibleProducts() {
    return compatibleProducts;
  }



  public void setCompatibleProducts(List<CompatibleProductDto> compatibleProducts) {
    this.compatibleProducts = compatibleProducts;
  }


  public CompatibleProductsListDto count(Integer count) {
    
    this.count = count;
    return this;
  }

   /**
   * Number of returned elements.
   * @return count
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Number of returned elements.")

  public Integer getCount() {
    return count;
  }



  public void setCount(Integer count) {
    this.count = count;
  }


  public CompatibleProductsListDto totalCount(Integer totalCount) {
    
    this.totalCount = totalCount;
    return this;
  }

   /**
   * Total number of available elements. Field is not present when &#x60;phrase&#x60; parameter is used.
   * @return totalCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1448", value = "Total number of available elements. Field is not present when `phrase` parameter is used.")

  public Integer getTotalCount() {
    return totalCount;
  }



  public void setTotalCount(Integer totalCount) {
    this.totalCount = totalCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompatibleProductsListDto compatibleProductsListDto = (CompatibleProductsListDto) o;
    return Objects.equals(this.compatibleProducts, compatibleProductsListDto.compatibleProducts) &&
        Objects.equals(this.count, compatibleProductsListDto.count) &&
        Objects.equals(this.totalCount, compatibleProductsListDto.totalCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(compatibleProducts, count, totalCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompatibleProductsListDto {\n");
    sb.append("    compatibleProducts: ").append(toIndentedString(compatibleProducts)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

