/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package observer.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Rules for the shipping cost for the first item in the parcel.
 */
@ApiModel(description = "Rules for the shipping cost for the first item in the parcel.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class InlineResponse2001ShippingRatesConstraintsFirstItemRate {
  public static final String SERIALIZED_NAME_MIN = "min";
  @SerializedName(SERIALIZED_NAME_MIN)
  private Double min;

  public static final String SERIALIZED_NAME_MAX = "max";
  @SerializedName(SERIALIZED_NAME_MAX)
  private Double max;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private String currency;


  public InlineResponse2001ShippingRatesConstraintsFirstItemRate min(Double min) {
    
    this.min = min;
    return this;
  }

   /**
   * Lower limit for the rate.
   * minimum: 0.0
   * maximum: 1.0E+8
   * @return min
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0.0", value = "Lower limit for the rate.")

  public Double getMin() {
    return min;
  }



  public void setMin(Double min) {
    this.min = min;
  }


  public InlineResponse2001ShippingRatesConstraintsFirstItemRate max(Double max) {
    
    this.max = max;
    return this;
  }

   /**
   * Upper limit for the rate.
   * minimum: 0.0
   * maximum: 1.0E+8
   * @return max
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "8.99", value = "Upper limit for the rate.")

  public Double getMax() {
    return max;
  }



  public void setMax(Double max) {
    this.max = max;
  }


  public InlineResponse2001ShippingRatesConstraintsFirstItemRate currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * ISO 4217 currency code.
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "PLN", value = "ISO 4217 currency code.")

  public String getCurrency() {
    return currency;
  }



  public void setCurrency(String currency) {
    this.currency = currency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001ShippingRatesConstraintsFirstItemRate inlineResponse2001ShippingRatesConstraintsFirstItemRate = (InlineResponse2001ShippingRatesConstraintsFirstItemRate) o;
    return Objects.equals(this.min, inlineResponse2001ShippingRatesConstraintsFirstItemRate.min) &&
        Objects.equals(this.max, inlineResponse2001ShippingRatesConstraintsFirstItemRate.max) &&
        Objects.equals(this.currency, inlineResponse2001ShippingRatesConstraintsFirstItemRate.currency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(min, max, currency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001ShippingRatesConstraintsFirstItemRate {\n");
    sb.append("    min: ").append(toIndentedString(min)).append("\n");
    sb.append("    max: ").append(toIndentedString(max)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

