/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package observer.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * ListingResponseFiltersValues
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class ListingResponseFiltersValues {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;

  public static final String SERIALIZED_NAME_ID_SUFFIX = "idSuffix";
  @SerializedName(SERIALIZED_NAME_ID_SUFFIX)
  private String idSuffix;

  public static final String SERIALIZED_NAME_COUNT = "count";
  @SerializedName(SERIALIZED_NAME_COUNT)
  private Integer count;

  public static final String SERIALIZED_NAME_SELECTED = "selected";
  @SerializedName(SERIALIZED_NAME_SELECTED)
  private Boolean selected;


  public ListingResponseFiltersValues name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the option; for NUMERIC parameters - word indicating start or end of range (i.e. *from*, *to*).
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "raty zero", value = "Name of the option; for NUMERIC parameters - word indicating start or end of range (i.e. *from*, *to*).")

  public String getName() {
    return name;
  }



  public void setName(String name) {
    this.name = name;
  }


  public ListingResponseFiltersValues value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * Filter value. Should be used as query parameter value in the request. This can be:   - for MULTI and SINGLE parameters - a value identifier (e.g. KUJAWSKO_POMORSKIE option in location.province  filter),  - for other types - a value entered by user.
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "INSTALLMENTS_ZERO", value = "Filter value. Should be used as query parameter value in the request. This can be:   - for MULTI and SINGLE parameters - a value identifier (e.g. KUJAWSKO_POMORSKIE option in location.province  filter),  - for other types - a value entered by user.")

  public String getValue() {
    return value;
  }



  public void setValue(String value) {
    this.value = value;
  }


  public ListingResponseFiltersValues idSuffix(String idSuffix) {
    
    this.idSuffix = idSuffix;
    return this;
  }

   /**
   * Suffix used as a second part of query parameter name to be used in the request (the first part is the filter ID). Applicable for NUMERIC values only.
   * @return idSuffix
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = ".to", value = "Suffix used as a second part of query parameter name to be used in the request (the first part is the filter ID). Applicable for NUMERIC values only.")

  public String getIdSuffix() {
    return idSuffix;
  }



  public void setIdSuffix(String idSuffix) {
    this.idSuffix = idSuffix;
  }


  public ListingResponseFiltersValues count(Integer count) {
    
    this.count = count;
    return this;
  }

   /**
   * Number of search results matching this filter value.
   * @return count
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "123", value = "Number of search results matching this filter value.")

  public Integer getCount() {
    return count;
  }



  public void setCount(Integer count) {
    this.count = count;
  }


  public ListingResponseFiltersValues selected(Boolean selected) {
    
    this.selected = selected;
    return this;
  }

   /**
   * Indicates whether this filter value was used in the current request.
   * @return selected
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates whether this filter value was used in the current request.")

  public Boolean getSelected() {
    return selected;
  }



  public void setSelected(Boolean selected) {
    this.selected = selected;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListingResponseFiltersValues listingResponseFiltersValues = (ListingResponseFiltersValues) o;
    return Objects.equals(this.name, listingResponseFiltersValues.name) &&
        Objects.equals(this.value, listingResponseFiltersValues.value) &&
        Objects.equals(this.idSuffix, listingResponseFiltersValues.idSuffix) &&
        Objects.equals(this.count, listingResponseFiltersValues.count) &&
        Objects.equals(this.selected, listingResponseFiltersValues.selected);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, value, idSuffix, count, selected);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListingResponseFiltersValues {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    idSuffix: ").append(toIndentedString(idSuffix)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    selected: ").append(toIndentedString(selected)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

