/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package observer.application.service.source.allegro.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.Objects;

/**
 * Allows you to change duration of offers. You can include only property in a request \&quot;duration\&quot; or \&quot;durationUnlimited\&quot;.
 */
@ApiModel(description = "Allows you to change duration of offers. You can include only property in a request \"duration\" or \"durationUnlimited\".")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class ModificationPublication {
  /**
   * Offer duration time provided in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
   */
  @JsonAdapter(DurationEnum.Adapter.class)
  public enum DurationEnum {
    PT72H("PT72H"),
    
    PT120H("PT120H"),
    
    PT168H("PT168H"),
    
    PT240H("PT240H"),
    
    PT480H("PT480H"),
    
    PT720H("PT720H"),
    
    P3D("P3D"),
    
    P5D("P5D"),
    
    P7D("P7D"),
    
    P10D("P10D"),
    
    P20D("P20D"),
    
    P30D("P30D");

    private String value;

    DurationEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DurationEnum fromValue(String value) {
      for (DurationEnum b : DurationEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DurationEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DurationEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DurationEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return DurationEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_DURATION = "duration";
  @SerializedName(SERIALIZED_NAME_DURATION)
  private DurationEnum duration;

  public static final String SERIALIZED_NAME_DURATION_UNLIMITED = "durationUnlimited";
  @SerializedName(SERIALIZED_NAME_DURATION_UNLIMITED)
  private Boolean durationUnlimited;


  public ModificationPublication duration(DurationEnum duration) {
    
    this.duration = duration;
    return this;
  }

   /**
   * Offer duration time provided in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
   * @return duration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Offer duration time provided in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.")

  public DurationEnum getDuration() {
    return duration;
  }



  public void setDuration(DurationEnum duration) {
    this.duration = duration;
  }


  public ModificationPublication durationUnlimited(Boolean durationUnlimited) {
    
    this.durationUnlimited = durationUnlimited;
    return this;
  }

   /**
   * Unlimited duration time.
   * @return durationUnlimited
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Unlimited duration time.")

  public Boolean getDurationUnlimited() {
    return durationUnlimited;
  }



  public void setDurationUnlimited(Boolean durationUnlimited) {
    this.durationUnlimited = durationUnlimited;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModificationPublication modificationPublication = (ModificationPublication) o;
    return Objects.equals(this.duration, modificationPublication.duration) &&
        Objects.equals(this.durationUnlimited, modificationPublication.durationUnlimited);
  }

  @Override
  public int hashCode() {
    return Objects.hash(duration, durationUnlimited);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModificationPublication {\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    durationUnlimited: ").append(toIndentedString(durationUnlimited)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

