/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package observer.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * This section is available only for offers with a defined end of publication.
 */
@ApiModel(description = "This section is available only for offers with a defined end of publication.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class OfferPublication {
  public static final String SERIALIZED_NAME_ENDING_AT = "endingAt";
  @SerializedName(SERIALIZED_NAME_ENDING_AT)
  private String endingAt;


  public OfferPublication endingAt(String endingAt) {
    
    this.endingAt = endingAt;
    return this;
  }

   /**
   * Publication ending date and time in UTC.
   * @return endingAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2019-05-15T18:09:41.000Z", value = "Publication ending date and time in UTC.")

  public String getEndingAt() {
    return endingAt;
  }



  public void setEndingAt(String endingAt) {
    this.endingAt = endingAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OfferPublication offerPublication = (OfferPublication) o;
    return Objects.equals(this.endingAt, offerPublication.endingAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endingAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OfferPublication {\n");
    sb.append("    endingAt: ").append(toIndentedString(endingAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

