/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package observer.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ProposeSaleProductRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class ProposeSaleProductRequest {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  private Category category;

  public static final String SERIALIZED_NAME_EANS = "eans";
  @SerializedName(SERIALIZED_NAME_EANS)
  private List<String> eans = null;

  public static final String SERIALIZED_NAME_IMAGES = "images";
  @SerializedName(SERIALIZED_NAME_IMAGES)
  private List<ImageUrl> images = new ArrayList<ImageUrl>();

  public static final String SERIALIZED_NAME_PARAMETERS = "parameters";
  @SerializedName(SERIALIZED_NAME_PARAMETERS)
  private List<ProductParameter> parameters = new ArrayList<ProductParameter>();

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private StandardizedDescription description;


  public ProposeSaleProductRequest name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Suggested product name.
   * @return name
  **/
  @ApiModelProperty(example = "iPhone 5s", required = true, value = "Suggested product name.")

  public String getName() {
    return name;
  }



  public void setName(String name) {
    this.name = name;
  }


  public ProposeSaleProductRequest category(Category category) {
    
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @ApiModelProperty(required = true, value = "")

  public Category getCategory() {
    return category;
  }



  public void setCategory(Category category) {
    this.category = category;
  }


  public ProposeSaleProductRequest eans(List<String> eans) {
    
    this.eans = eans;
    return this;
  }

  public ProposeSaleProductRequest addEansItem(String eansItem) {
    if (this.eans == null) {
      this.eans = new ArrayList<String>();
    }
    this.eans.add(eansItem);
    return this;
  }

   /**
   * A list of codes that identify this product. Currently this can include EAN, ISBN, and UPC identifier types.
   * @return eans
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[\"0019062113399\",\"0000007905193\"]", value = "A list of codes that identify this product. Currently this can include EAN, ISBN, and UPC identifier types.")

  public List<String> getEans() {
    return eans;
  }



  public void setEans(List<String> eans) {
    this.eans = eans;
  }


  public ProposeSaleProductRequest images(List<ImageUrl> images) {
    
    this.images = images;
    return this;
  }

  public ProposeSaleProductRequest addImagesItem(ImageUrl imagesItem) {
    this.images.add(imagesItem);
    return this;
  }

   /**
   * List of product images. At least one image is required.
   * @return images
  **/
  @ApiModelProperty(required = true, value = "List of product images. At least one image is required.")

  public List<ImageUrl> getImages() {
    return images;
  }



  public void setImages(List<ImageUrl> images) {
    this.images = images;
  }


  public ProposeSaleProductRequest parameters(List<ProductParameter> parameters) {
    
    this.parameters = parameters;
    return this;
  }

  public ProposeSaleProductRequest addParametersItem(ProductParameter parametersItem) {
    this.parameters.add(parametersItem);
    return this;
  }

   /**
   * List of product parameters.
   * @return parameters
  **/
  @ApiModelProperty(required = true, value = "List of product parameters.")

  public List<ProductParameter> getParameters() {
    return parameters;
  }



  public void setParameters(List<ProductParameter> parameters) {
    this.parameters = parameters;
  }


  public ProposeSaleProductRequest description(StandardizedDescription description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public StandardizedDescription getDescription() {
    return description;
  }



  public void setDescription(StandardizedDescription description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProposeSaleProductRequest proposeSaleProductRequest = (ProposeSaleProductRequest) o;
    return Objects.equals(this.name, proposeSaleProductRequest.name) &&
        Objects.equals(this.category, proposeSaleProductRequest.category) &&
        Objects.equals(this.eans, proposeSaleProductRequest.eans) &&
        Objects.equals(this.images, proposeSaleProductRequest.images) &&
        Objects.equals(this.parameters, proposeSaleProductRequest.parameters) &&
        Objects.equals(this.description, proposeSaleProductRequest.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, category, eans, images, parameters, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProposeSaleProductRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    eans: ").append(toIndentedString(eans)).append("\n");
    sb.append("    images: ").append(toIndentedString(images)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

