/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package observer.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Summary of data concerning users that do not recommend the seller.
 */
@ApiModel(description = "Summary of data concerning users that do not recommend the seller.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class UserRatingSummaryResponseNotRecommended {
  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private Long total;

  public static final String SERIALIZED_NAME_UNIQUE = "unique";
  @SerializedName(SERIALIZED_NAME_UNIQUE)
  private Long unique;


  public UserRatingSummaryResponseNotRecommended total(Long total) {
    
    this.total = total;
    return this;
  }

   /**
   * Total number of negative feedbacks received.
   * @return total
  **/
  @ApiModelProperty(example = "100", required = true, value = "Total number of negative feedbacks received.")

  public Long getTotal() {
    return total;
  }



  public void setTotal(Long total) {
    this.total = total;
  }


  public UserRatingSummaryResponseNotRecommended unique(Long unique) {
    
    this.unique = unique;
    return this;
  }

   /**
   * Number of unique users.
   * @return unique
  **/
  @ApiModelProperty(example = "80", required = true, value = "Number of unique users.")

  public Long getUnique() {
    return unique;
  }



  public void setUnique(Long unique) {
    this.unique = unique;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserRatingSummaryResponseNotRecommended userRatingSummaryResponseNotRecommended = (UserRatingSummaryResponseNotRecommended) o;
    return Objects.equals(this.total, userRatingSummaryResponseNotRecommended.total) &&
        Objects.equals(this.unique, userRatingSummaryResponseNotRecommended.unique);
  }

  @Override
  public int hashCode() {
    return Objects.hash(total, unique);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserRatingSummaryResponseNotRecommended {\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    unique: ").append(toIndentedString(unique)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

