/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package observer.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * WrapperTypeForPreviewConditions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class WrapperTypeForPreviewConditions {
  public static final String SERIALIZED_NAME_INCLUDE_QUOTING_BUNDLES = "includeQuotingBundles";
  @SerializedName(SERIALIZED_NAME_INCLUDE_QUOTING_BUNDLES)
  private Boolean includeQuotingBundles;

  public static final String SERIALIZED_NAME_OFFER = "offer";
  @SerializedName(SERIALIZED_NAME_OFFER)
  private ParametersForPreviewPrice offer;


  public WrapperTypeForPreviewConditions includeQuotingBundles(Boolean includeQuotingBundles) {
    
    this.includeQuotingBundles = includeQuotingBundles;
    return this;
  }

   /**
   * Include in calculation user&#39;s active bundles which allow to publish for free offer or use for free promotion options.
   * @return includeQuotingBundles
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Include in calculation user's active bundles which allow to publish for free offer or use for free promotion options.")

  public Boolean getIncludeQuotingBundles() {
    return includeQuotingBundles;
  }



  public void setIncludeQuotingBundles(Boolean includeQuotingBundles) {
    this.includeQuotingBundles = includeQuotingBundles;
  }


  public WrapperTypeForPreviewConditions offer(ParametersForPreviewPrice offer) {
    
    this.offer = offer;
    return this;
  }

   /**
   * Get offer
   * @return offer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ParametersForPreviewPrice getOffer() {
    return offer;
  }



  public void setOffer(ParametersForPreviewPrice offer) {
    this.offer = offer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WrapperTypeForPreviewConditions wrapperTypeForPreviewConditions = (WrapperTypeForPreviewConditions) o;
    return Objects.equals(this.includeQuotingBundles, wrapperTypeForPreviewConditions.includeQuotingBundles) &&
        Objects.equals(this.offer, wrapperTypeForPreviewConditions.offer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(includeQuotingBundles, offer);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WrapperTypeForPreviewConditions {\n");
    sb.append("    includeQuotingBundles: ").append(toIndentedString(includeQuotingBundles)).append("\n");
    sb.append("    offer: ").append(toIndentedString(offer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

