/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * BadgeApplicationRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class BadgeApplicationRequest {
  public static final String SERIALIZED_NAME_CAMPAIGN = "campaign";
  @SerializedName(SERIALIZED_NAME_CAMPAIGN)
  private BadgeApplicationCampaign campaign;

  public static final String SERIALIZED_NAME_OFFER = "offer";
  @SerializedName(SERIALIZED_NAME_OFFER)
  private BadgeApplicationOffer offer;

  public static final String SERIALIZED_NAME_PRICES = "prices";
  @SerializedName(SERIALIZED_NAME_PRICES)
  private BadgeApplicationPrices prices;


  public BadgeApplicationRequest campaign(BadgeApplicationCampaign campaign) {
    
    this.campaign = campaign;
    return this;
  }

   /**
   * Get campaign
   * @return campaign
  **/
  @ApiModelProperty(required = true, value = "")

  public BadgeApplicationCampaign getCampaign() {
    return campaign;
  }



  public void setCampaign(BadgeApplicationCampaign campaign) {
    this.campaign = campaign;
  }


  public BadgeApplicationRequest offer(BadgeApplicationOffer offer) {
    
    this.offer = offer;
    return this;
  }

   /**
   * Get offer
   * @return offer
  **/
  @ApiModelProperty(required = true, value = "")

  public BadgeApplicationOffer getOffer() {
    return offer;
  }



  public void setOffer(BadgeApplicationOffer offer) {
    this.offer = offer;
  }


  public BadgeApplicationRequest prices(BadgeApplicationPrices prices) {
    
    this.prices = prices;
    return this;
  }

   /**
   * Get prices
   * @return prices
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BadgeApplicationPrices getPrices() {
    return prices;
  }



  public void setPrices(BadgeApplicationPrices prices) {
    this.prices = prices;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BadgeApplicationRequest badgeApplicationRequest = (BadgeApplicationRequest) o;
    return Objects.equals(this.campaign, badgeApplicationRequest.campaign) &&
        Objects.equals(this.offer, badgeApplicationRequest.offer) &&
        Objects.equals(this.prices, badgeApplicationRequest.prices);
  }

  @Override
  public int hashCode() {
    return Objects.hash(campaign, offer, prices);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BadgeApplicationRequest {\n");
    sb.append("    campaign: ").append(toIndentedString(campaign)).append("\n");
    sb.append("    offer: ").append(toIndentedString(offer)).append("\n");
    sb.append("    prices: ").append(toIndentedString(prices)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

