/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * CheckoutFormAdditionalService
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class CheckoutFormAdditionalService {
  public static final String SERIALIZED_NAME_DEFINITION_ID = "definitionId";
  @SerializedName(SERIALIZED_NAME_DEFINITION_ID)
  private String definitionId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private Price price;

  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  private Integer quantity;


  public CheckoutFormAdditionalService definitionId(String definitionId) {
    
    this.definitionId = definitionId;
    return this;
  }

   /**
   * Additional service id
   * @return definitionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "CARRY_IN", value = "Additional service id")

  public String getDefinitionId() {
    return definitionId;
  }



  public void setDefinitionId(String definitionId) {
    this.definitionId = definitionId;
  }


  public CheckoutFormAdditionalService name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Additional service name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Wniesienie", value = "Additional service name")

  public String getName() {
    return name;
  }



  public void setName(String name) {
    this.name = name;
  }


  public CheckoutFormAdditionalService price(Price price) {
    
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Price getPrice() {
    return price;
  }



  public void setPrice(Price price) {
    this.price = price;
  }


  public CheckoutFormAdditionalService quantity(Integer quantity) {
    
    this.quantity = quantity;
    return this;
  }

   /**
   * Quantity of an additional service
   * @return quantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Quantity of an additional service")

  public Integer getQuantity() {
    return quantity;
  }



  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckoutFormAdditionalService checkoutFormAdditionalService = (CheckoutFormAdditionalService) o;
    return Objects.equals(this.definitionId, checkoutFormAdditionalService.definitionId) &&
        Objects.equals(this.name, checkoutFormAdditionalService.name) &&
        Objects.equals(this.price, checkoutFormAdditionalService.price) &&
        Objects.equals(this.quantity, checkoutFormAdditionalService.quantity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(definitionId, name, price, quantity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckoutFormAdditionalService {\n");
    sb.append("    definitionId: ").append(toIndentedString(definitionId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

