/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * CheckoutFormDeliveryPickupPointAddress
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class CheckoutFormDeliveryPickupPointAddress {
  public static final String SERIALIZED_NAME_STREET = "street";
  @SerializedName(SERIALIZED_NAME_STREET)
  private String street;

  public static final String SERIALIZED_NAME_ZIP_CODE = "zipCode";
  @SerializedName(SERIALIZED_NAME_ZIP_CODE)
  private String zipCode;

  public static final String SERIALIZED_NAME_CITY = "city";
  @SerializedName(SERIALIZED_NAME_CITY)
  private String city;


  public CheckoutFormDeliveryPickupPointAddress street(String street) {
    
    this.street = street;
    return this;
  }

   /**
   * Delivery point street name
   * @return street
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Grunwaldzka 108", value = "Delivery point street name")

  public String getStreet() {
    return street;
  }



  public void setStreet(String street) {
    this.street = street;
  }


  public CheckoutFormDeliveryPickupPointAddress zipCode(String zipCode) {
    
    this.zipCode = zipCode;
    return this;
  }

   /**
   * Delivery point postal code
   * @return zipCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "60-166", value = "Delivery point postal code")

  public String getZipCode() {
    return zipCode;
  }



  public void setZipCode(String zipCode) {
    this.zipCode = zipCode;
  }


  public CheckoutFormDeliveryPickupPointAddress city(String city) {
    
    this.city = city;
    return this;
  }

   /**
   * City name
   * @return city
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Poznań", value = "City name")

  public String getCity() {
    return city;
  }



  public void setCity(String city) {
    this.city = city;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckoutFormDeliveryPickupPointAddress checkoutFormDeliveryPickupPointAddress = (CheckoutFormDeliveryPickupPointAddress) o;
    return Objects.equals(this.street, checkoutFormDeliveryPickupPointAddress.street) &&
        Objects.equals(this.zipCode, checkoutFormDeliveryPickupPointAddress.zipCode) &&
        Objects.equals(this.city, checkoutFormDeliveryPickupPointAddress.city);
  }

  @Override
  public int hashCode() {
    return Objects.hash(street, zipCode, city);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckoutFormDeliveryPickupPointAddress {\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    zipCode: ").append(toIndentedString(zipCode)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

