/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.allegro.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * Payment type
 */
@JsonAdapter(CheckoutFormPaymentType.Adapter.class)
public enum CheckoutFormPaymentType {
  
  CASH_ON_DELIVERY("CASH_ON_DELIVERY"),
  
  WIRE_TRANSFER("WIRE_TRANSFER"),
  
  ONLINE("ONLINE");

  private String value;

  CheckoutFormPaymentType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CheckoutFormPaymentType fromValue(String value) {
    for (CheckoutFormPaymentType b : CheckoutFormPaymentType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<CheckoutFormPaymentType> {
    @Override
    public void write(final JsonWriter jsonWriter, final CheckoutFormPaymentType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CheckoutFormPaymentType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CheckoutFormPaymentType.fromValue(value);
    }
  }
}

