/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ClassifiedPackages
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class ClassifiedPackages {
  public static final String SERIALIZED_NAME_BASE_PACKAGE = "basePackage";
  @SerializedName(SERIALIZED_NAME_BASE_PACKAGE)
  private ClassifiedPackage basePackage;

  public static final String SERIALIZED_NAME_EXTRA_PACKAGES = "extraPackages";
  @SerializedName(SERIALIZED_NAME_EXTRA_PACKAGES)
  private List<ClassifiedPackage> extraPackages = null;


  public ClassifiedPackages basePackage(ClassifiedPackage basePackage) {
    
    this.basePackage = basePackage;
    return this;
  }

   /**
   * Get basePackage
   * @return basePackage
  **/
  @ApiModelProperty(required = true, value = "")

  public ClassifiedPackage getBasePackage() {
    return basePackage;
  }



  public void setBasePackage(ClassifiedPackage basePackage) {
    this.basePackage = basePackage;
  }


  public ClassifiedPackages extraPackages(List<ClassifiedPackage> extraPackages) {
    
    this.extraPackages = extraPackages;
    return this;
  }

  public ClassifiedPackages addExtraPackagesItem(ClassifiedPackage extraPackagesItem) {
    if (this.extraPackages == null) {
      this.extraPackages = new ArrayList<ClassifiedPackage>();
    }
    this.extraPackages.add(extraPackagesItem);
    return this;
  }

   /**
   * Get extraPackages
   * @return extraPackages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ClassifiedPackage> getExtraPackages() {
    return extraPackages;
  }



  public void setExtraPackages(List<ClassifiedPackage> extraPackages) {
    this.extraPackages = extraPackages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClassifiedPackages classifiedPackages = (ClassifiedPackages) o;
    return Objects.equals(this.basePackage, classifiedPackages.basePackage) &&
        Objects.equals(this.extraPackages, classifiedPackages.extraPackages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(basePackage, extraPackages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClassifiedPackages {\n");
    sb.append("    basePackage: ").append(toIndentedString(basePackage)).append("\n");
    sb.append("    extraPackages: ").append(toIndentedString(extraPackages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

