/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * DisputeAuthor
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class DisputeAuthor {
  public static final String SERIALIZED_NAME_LOGIN = "login";
  @SerializedName(SERIALIZED_NAME_LOGIN)
  private String login;

  public static final String SERIALIZED_NAME_ROLE = "role";
  @SerializedName(SERIALIZED_NAME_ROLE)
  private DisputeAuthorRole role;


  public DisputeAuthor login(String login) {
    
    this.login = login;
    return this;
  }

   /**
   * Not present if role is ADMIN
   * @return login
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Not present if role is ADMIN")

  public String getLogin() {
    return login;
  }



  public void setLogin(String login) {
    this.login = login;
  }


  public DisputeAuthor role(DisputeAuthorRole role) {
    
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  @ApiModelProperty(required = true, value = "")

  public DisputeAuthorRole getRole() {
    return role;
  }



  public void setRole(DisputeAuthorRole role) {
    this.role = role;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DisputeAuthor disputeAuthor = (DisputeAuthor) o;
    return Objects.equals(this.login, disputeAuthor.login) &&
        Objects.equals(this.role, disputeAuthor.role);
  }

  @Override
  public int hashCode() {
    return Objects.hash(login, role);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DisputeAuthor {\n");
    sb.append("    login: ").append(toIndentedString(login)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

