/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * DisputeListResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class DisputeListResponse {
  public static final String SERIALIZED_NAME_DISPUTES = "disputes";
  @SerializedName(SERIALIZED_NAME_DISPUTES)
  private List<Dispute> disputes = null;


  public DisputeListResponse disputes(List<Dispute> disputes) {
    
    this.disputes = disputes;
    return this;
  }

  public DisputeListResponse addDisputesItem(Dispute disputesItem) {
    if (this.disputes == null) {
      this.disputes = new ArrayList<Dispute>();
    }
    this.disputes.add(disputesItem);
    return this;
  }

   /**
   * Get disputes
   * @return disputes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Dispute> getDisputes() {
    return disputes;
  }



  public void setDisputes(List<Dispute> disputes) {
    this.disputes = disputes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DisputeListResponse disputeListResponse = (DisputeListResponse) o;
    return Objects.equals(this.disputes, disputeListResponse.disputes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disputes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DisputeListResponse {\n");
    sb.append("    disputes: ").append(toIndentedString(disputes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

