/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Available sort options.
 */
@ApiModel(description = "Available sort options.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class ListingResponseSort {
  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_ORDER = "order";
  @SerializedName(SERIALIZED_NAME_ORDER)
  private String order;

  public static final String SERIALIZED_NAME_SELECTED = "selected";
  @SerializedName(SERIALIZED_NAME_SELECTED)
  private Boolean selected;


  public ListingResponseSort value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * The query parameter value which should be used for this sorting option.
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "-relevance", value = "The query parameter value which should be used for this sorting option.")

  public String getValue() {
    return value;
  }



  public void setValue(String value) {
    this.value = value;
  }


  public ListingResponseSort name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The sorting option name in Polish.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "trafność", value = "The sorting option name in Polish.")

  public String getName() {
    return name;
  }



  public void setName(String name) {
    this.name = name;
  }


  public ListingResponseSort order(String order) {
    
    this.order = order;
    return this;
  }

   /**
   * The order label in Polish specifying ascending or descending mode.
   * @return order
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "największa", value = "The order label in Polish specifying ascending or descending mode.")

  public String getOrder() {
    return order;
  }



  public void setOrder(String order) {
    this.order = order;
  }


  public ListingResponseSort selected(Boolean selected) {
    
    this.selected = selected;
    return this;
  }

   /**
   * Indicates whether this sorting option was used in the current request.
   * @return selected
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates whether this sorting option was used in the current request.")

  public Boolean getSelected() {
    return selected;
  }



  public void setSelected(Boolean selected) {
    this.selected = selected;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListingResponseSort listingResponseSort = (ListingResponseSort) o;
    return Objects.equals(this.value, listingResponseSort.value) &&
        Objects.equals(this.name, listingResponseSort.name) &&
        Objects.equals(this.order, listingResponseSort.order) &&
        Objects.equals(this.selected, listingResponseSort.selected);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, name, order, selected);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListingResponseSort {\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    selected: ").append(toIndentedString(selected)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

