/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * OfferEventEndedOffer
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class OfferEventEndedOffer {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_PUBLICATION = "publication";
  @SerializedName(SERIALIZED_NAME_PUBLICATION)
  private OfferEventEndedOfferAllOfPublication publication;


  public OfferEventEndedOffer id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The offer ID.
   * @return id
  **/
  @ApiModelProperty(example = "2865624934", required = true, value = "The offer ID.")

  public String getId() {
    return id;
  }



  public void setId(String id) {
    this.id = id;
  }


  public OfferEventEndedOffer publication(OfferEventEndedOfferAllOfPublication publication) {
    
    this.publication = publication;
    return this;
  }

   /**
   * Get publication
   * @return publication
  **/
  @ApiModelProperty(required = true, value = "")

  public OfferEventEndedOfferAllOfPublication getPublication() {
    return publication;
  }



  public void setPublication(OfferEventEndedOfferAllOfPublication publication) {
    this.publication = publication;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OfferEventEndedOffer offerEventEndedOffer = (OfferEventEndedOffer) o;
    return Objects.equals(this.id, offerEventEndedOffer.id) &&
        Objects.equals(this.publication, offerEventEndedOffer.publication);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, publication);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OfferEventEndedOffer {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    publication: ").append(toIndentedString(publication)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

