/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Price modification command payload
 */
@ApiModel(description = "Price modification command payload")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class OfferPriceChangeCommand {
  public static final String SERIALIZED_NAME_MODIFICATION = "modification";
  @SerializedName(SERIALIZED_NAME_MODIFICATION)
  private PriceModification modification;

  public static final String SERIALIZED_NAME_OFFER_CRITERIA = "offerCriteria";
  @SerializedName(SERIALIZED_NAME_OFFER_CRITERIA)
  private List<OfferCriterium> offerCriteria = null;


  public OfferPriceChangeCommand modification(PriceModification modification) {
    
    this.modification = modification;
    return this;
  }

   /**
   * Get modification
   * @return modification
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PriceModification getModification() {
    return modification;
  }



  public void setModification(PriceModification modification) {
    this.modification = modification;
  }


  public OfferPriceChangeCommand offerCriteria(List<OfferCriterium> offerCriteria) {
    
    this.offerCriteria = offerCriteria;
    return this;
  }

  public OfferPriceChangeCommand addOfferCriteriaItem(OfferCriterium offerCriteriaItem) {
    if (this.offerCriteria == null) {
      this.offerCriteria = new ArrayList<OfferCriterium>();
    }
    this.offerCriteria.add(offerCriteriaItem);
    return this;
  }

   /**
   * List of offer criteria
   * @return offerCriteria
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of offer criteria")

  public List<OfferCriterium> getOfferCriteria() {
    return offerCriteria;
  }



  public void setOfferCriteria(List<OfferCriterium> offerCriteria) {
    this.offerCriteria = offerCriteria;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OfferPriceChangeCommand offerPriceChangeCommand = (OfferPriceChangeCommand) o;
    return Objects.equals(this.modification, offerPriceChangeCommand.modification) &&
        Objects.equals(this.offerCriteria, offerPriceChangeCommand.offerCriteria);
  }

  @Override
  public int hashCode() {
    return Objects.hash(modification, offerCriteria);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OfferPriceChangeCommand {\n");
    sb.append("    modification: ").append(toIndentedString(modification)).append("\n");
    sb.append("    offerCriteria: ").append(toIndentedString(offerCriteria)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

