/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Information about promotion options for the item.
 */
@ApiModel(description = "Information about promotion options for the item.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class OfferPromotion {
  public static final String SERIALIZED_NAME_EMPHASIZED = "emphasized";
  @SerializedName(SERIALIZED_NAME_EMPHASIZED)
  private Boolean emphasized;

  public static final String SERIALIZED_NAME_BOLD = "bold";
  @SerializedName(SERIALIZED_NAME_BOLD)
  private Boolean bold;

  public static final String SERIALIZED_NAME_HIGHLIGHT = "highlight";
  @SerializedName(SERIALIZED_NAME_HIGHLIGHT)
  private Boolean highlight;


  public OfferPromotion emphasized(Boolean emphasized) {
    
    this.emphasized = emphasized;
    return this;
  }

   /**
   * Indicates whether the offer is promoted.
   * @return emphasized
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates whether the offer is promoted.")

  public Boolean getEmphasized() {
    return emphasized;
  }



  public void setEmphasized(Boolean emphasized) {
    this.emphasized = emphasized;
  }


  public OfferPromotion bold(Boolean bold) {
    
    this.bold = bold;
    return this;
  }

   /**
   * Indicates whether the offer has bold title option.
   * @return bold
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates whether the offer has bold title option.")

  public Boolean getBold() {
    return bold;
  }



  public void setBold(Boolean bold) {
    this.bold = bold;
  }


  public OfferPromotion highlight(Boolean highlight) {
    
    this.highlight = highlight;
    return this;
  }

   /**
   * Indicates whether the offer has highlight option.
   * @return highlight
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates whether the offer has highlight option.")

  public Boolean getHighlight() {
    return highlight;
  }



  public void setHighlight(Boolean highlight) {
    this.highlight = highlight;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OfferPromotion offerPromotion = (OfferPromotion) o;
    return Objects.equals(this.emphasized, offerPromotion.emphasized) &&
        Objects.equals(this.bold, offerPromotion.bold) &&
        Objects.equals(this.highlight, offerPromotion.highlight);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emphasized, bold, highlight);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OfferPromotion {\n");
    sb.append("    emphasized: ").append(toIndentedString(emphasized)).append("\n");
    sb.append("    bold: ").append(toIndentedString(bold)).append("\n");
    sb.append("    highlight: ").append(toIndentedString(highlight)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

