/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

/**
 * Order event
 */
@ApiModel(description = "Order event")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class OrderEvent {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_ORDER = "order";
  @SerializedName(SERIALIZED_NAME_ORDER)
  private OrderEventData order;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private CheckoutFormStatus type;

  public static final String SERIALIZED_NAME_OCCURRED_AT = "occurredAt";
  @SerializedName(SERIALIZED_NAME_OCCURRED_AT)
  private OffsetDateTime occurredAt;


  public OrderEvent id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * event id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "event id")

  public String getId() {
    return id;
  }



  public void setId(String id) {
    this.id = id;
  }


  public OrderEvent order(OrderEventData order) {
    
    this.order = order;
    return this;
  }

   /**
   * Get order
   * @return order
  **/
  @ApiModelProperty(required = true, value = "")

  public OrderEventData getOrder() {
    return order;
  }



  public void setOrder(OrderEventData order) {
    this.order = order;
  }


  public OrderEvent type(CheckoutFormStatus type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(required = true, value = "")

  public CheckoutFormStatus getType() {
    return type;
  }



  public void setType(CheckoutFormStatus type) {
    this.type = type;
  }


  public OrderEvent occurredAt(OffsetDateTime occurredAt) {
    
    this.occurredAt = occurredAt;
    return this;
  }

   /**
   * Date when the event occurred
   * @return occurredAt
  **/
  @ApiModelProperty(example = "2018-10-12T10:12:32.321Z", required = true, value = "Date when the event occurred")

  public OffsetDateTime getOccurredAt() {
    return occurredAt;
  }



  public void setOccurredAt(OffsetDateTime occurredAt) {
    this.occurredAt = occurredAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderEvent orderEvent = (OrderEvent) o;
    return Objects.equals(this.id, orderEvent.id) &&
        Objects.equals(this.order, orderEvent.order) &&
        Objects.equals(this.type, orderEvent.type) &&
        Objects.equals(this.occurredAt, orderEvent.occurredAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, order, type, occurredAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderEvent {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    occurredAt: ").append(toIndentedString(occurredAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

