/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * SaleProductResponseCategoriesDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class SaleProductResponseCategoriesDto {
  public static final String SERIALIZED_NAME_SUBCATEGORIES = "subcategories";
  @SerializedName(SERIALIZED_NAME_SUBCATEGORIES)
  private List<ProductsCategorySubcategories> subcategories = null;

  public static final String SERIALIZED_NAME_PATH = "path";
  @SerializedName(SERIALIZED_NAME_PATH)
  private List<ProductsCategoryPath> path = null;


  public SaleProductResponseCategoriesDto subcategories(List<ProductsCategorySubcategories> subcategories) {
    
    this.subcategories = subcategories;
    return this;
  }

  public SaleProductResponseCategoriesDto addSubcategoriesItem(ProductsCategorySubcategories subcategoriesItem) {
    if (this.subcategories == null) {
      this.subcategories = new ArrayList<ProductsCategorySubcategories>();
    }
    this.subcategories.add(subcategoriesItem);
    return this;
  }

   /**
   * A list of categories that contain results for given search parameters.
   * @return subcategories
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of categories that contain results for given search parameters.")

  public List<ProductsCategorySubcategories> getSubcategories() {
    return subcategories;
  }



  public void setSubcategories(List<ProductsCategorySubcategories> subcategories) {
    this.subcategories = subcategories;
  }


  public SaleProductResponseCategoriesDto path(List<ProductsCategoryPath> path) {
    
    this.path = path;
    return this;
  }

  public SaleProductResponseCategoriesDto addPathItem(ProductsCategoryPath pathItem) {
    if (this.path == null) {
      this.path = new ArrayList<ProductsCategoryPath>();
    }
    this.path.add(pathItem);
    return this;
  }

   /**
   * The path of current category used as categrory filter in search.
   * @return path
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The path of current category used as categrory filter in search.")

  public List<ProductsCategoryPath> getPath() {
    return path;
  }



  public void setPath(List<ProductsCategoryPath> path) {
    this.path = path;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SaleProductResponseCategoriesDto saleProductResponseCategoriesDto = (SaleProductResponseCategoriesDto) o;
    return Objects.equals(this.subcategories, saleProductResponseCategoriesDto.subcategories) &&
        Objects.equals(this.path, saleProductResponseCategoriesDto.path);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subcategories, path);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SaleProductResponseCategoriesDto {\n");
    sb.append("    subcategories: ").append(toIndentedString(subcategories)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

