/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * SearchResult
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class SearchResult {
  public static final String SERIALIZED_NAME_POS_LIST = "posList";
  @SerializedName(SERIALIZED_NAME_POS_LIST)
  private List<Pos> posList = null;


  public SearchResult posList(List<Pos> posList) {
    
    this.posList = posList;
    return this;
  }

  public SearchResult addPosListItem(Pos posListItem) {
    if (this.posList == null) {
      this.posList = new ArrayList<Pos>();
    }
    this.posList.add(posListItem);
    return this;
  }

   /**
   * Get posList
   * @return posList
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Pos> getPosList() {
    return posList;
  }



  public void setPosList(List<Pos> posList) {
    this.posList = posList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchResult searchResult = (SearchResult) o;
    return Objects.equals(this.posList, searchResult.posList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(posList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchResult {\n");
    sb.append("    posList: ").append(toIndentedString(posList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

