/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Information on the offer&#39;s selling mode.
 */
@ApiModel(description = "Information on the offer's selling mode.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class SellingMode {
  public static final String SERIALIZED_NAME_FORMAT = "format";
  @SerializedName(SERIALIZED_NAME_FORMAT)
  private SellingModeFormat format;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private BuyNowPrice price = null;

  public static final String SERIALIZED_NAME_MINIMAL_PRICE = "minimalPrice";
  @SerializedName(SERIALIZED_NAME_MINIMAL_PRICE)
  private MinimalPrice minimalPrice = null;

  public static final String SERIALIZED_NAME_STARTING_PRICE = "startingPrice";
  @SerializedName(SERIALIZED_NAME_STARTING_PRICE)
  private StartingPrice startingPrice = null;


  public SellingMode format(SellingModeFormat format) {
    
    this.format = format;
    return this;
  }

   /**
   * Get format
   * @return format
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SellingModeFormat getFormat() {
    return format;
  }



  public void setFormat(SellingModeFormat format) {
    this.format = format;
  }


  public SellingMode price(BuyNowPrice price) {
    
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BuyNowPrice getPrice() {
    return price;
  }



  public void setPrice(BuyNowPrice price) {
    this.price = price;
  }


  public SellingMode minimalPrice(MinimalPrice minimalPrice) {
    
    this.minimalPrice = minimalPrice;
    return this;
  }

   /**
   * Get minimalPrice
   * @return minimalPrice
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MinimalPrice getMinimalPrice() {
    return minimalPrice;
  }



  public void setMinimalPrice(MinimalPrice minimalPrice) {
    this.minimalPrice = minimalPrice;
  }


  public SellingMode startingPrice(StartingPrice startingPrice) {
    
    this.startingPrice = startingPrice;
    return this;
  }

   /**
   * Get startingPrice
   * @return startingPrice
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public StartingPrice getStartingPrice() {
    return startingPrice;
  }



  public void setStartingPrice(StartingPrice startingPrice) {
    this.startingPrice = startingPrice;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SellingMode sellingMode = (SellingMode) o;
    return Objects.equals(this.format, sellingMode.format) &&
        Objects.equals(this.price, sellingMode.price) &&
        Objects.equals(this.minimalPrice, sellingMode.minimalPrice) &&
        Objects.equals(this.startingPrice, sellingMode.startingPrice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(format, price, minimalPrice, startingPrice);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SellingMode {\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    minimalPrice: ").append(toIndentedString(minimalPrice)).append("\n");
    sb.append("    startingPrice: ").append(toIndentedString(startingPrice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

