/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Validation
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class Validation {
  public static final String SERIALIZED_NAME_ERRORS = "errors";
  @SerializedName(SERIALIZED_NAME_ERRORS)
  private List<ValidationError> errors = new ArrayList<ValidationError>();

  public static final String SERIALIZED_NAME_VALIDATED_AT = "validatedAt";
  @SerializedName(SERIALIZED_NAME_VALIDATED_AT)
  private OffsetDateTime validatedAt;


  public Validation errors(List<ValidationError> errors) {
    
    this.errors = errors;
    return this;
  }

  public Validation addErrorsItem(ValidationError errorsItem) {
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  @ApiModelProperty(required = true, value = "")

  public List<ValidationError> getErrors() {
    return errors;
  }



  public void setErrors(List<ValidationError> errors) {
    this.errors = errors;
  }


  public Validation validatedAt(OffsetDateTime validatedAt) {
    
    this.validatedAt = validatedAt;
    return this;
  }

   /**
   * Get validatedAt
   * @return validatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getValidatedAt() {
    return validatedAt;
  }



  public void setValidatedAt(OffsetDateTime validatedAt) {
    this.validatedAt = validatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Validation validation = (Validation) o;
    return Objects.equals(this.errors, validation.errors) &&
        Objects.equals(this.validatedAt, validation.validatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errors, validatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Validation {\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    validatedAt: ").append(toIndentedString(validatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

