observer:
  secured: false
  ftp:
    hostname: change-me
    username: change-me
    password: change-me
    filepath: change-me
  searches:
    error:
      threshold: 2
      delay: 20m
  items:
    retention: 90d
    notification-delay: 20s
  allegro:
    delay: 2m
    token-private: change-me
  allegro-lokalnie:
    delay: 10s
  olx:
    delay: 10s
  ebay:
    delay: 10s
    security-appname: change-me
  onesignal:
    app-id: change-me
    api-key: change-me
  chromedriver:
    logging: false
    arguments: change-me

server:
  port: 9130
  servlet:
    session:
      timeout: 7d

logging:
  level:
    root: info

spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:./database/observer
    driver-class-name: org.h2.Driver
    username: change-me
    password: change-me
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
  resources:
    cache:
      cachecontrol:
        max-age: 7d
  security:
    user:
      name: change-me
      password: change-me
  thymeleaf:
    cache: true