/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * BadgeApplication
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class BadgeApplication {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;

  public static final String SERIALIZED_NAME_CAMPAIGN = "campaign";
  @SerializedName(SERIALIZED_NAME_CAMPAIGN)
  private BadgeApplicationCampaign campaign;

  public static final String SERIALIZED_NAME_OFFER = "offer";
  @SerializedName(SERIALIZED_NAME_OFFER)
  private BadgeApplicationOffer offer;

  public static final String SERIALIZED_NAME_PRICES = "prices";
  @SerializedName(SERIALIZED_NAME_PRICES)
  private BadgeApplicationPrices prices;

  public static final String SERIALIZED_NAME_PROCESS = "process";
  @SerializedName(SERIALIZED_NAME_PROCESS)
  private BadgeApplicationProcess process;


  public BadgeApplication id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Badge application ID.
   * @return id
  **/
  @ApiModelProperty(example = "01234567-89ab-0123-456789ab", required = true, value = "Badge application ID.")

  public String getId() {
    return id;
  }



  public void setId(String id) {
    this.id = id;
  }


  public BadgeApplication createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Provided in [ISO 8601 format](link: https://en.wikipedia.org/wiki/ISO_8601).
   * @return createdAt
  **/
  @ApiModelProperty(example = "2011-12-03T10:15:30Z", required = true, value = "Provided in [ISO 8601 format](link: https://en.wikipedia.org/wiki/ISO_8601).")

  public String getCreatedAt() {
    return createdAt;
  }



  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public BadgeApplication updatedAt(String updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Provided in [ISO 8601 format](link: https://en.wikipedia.org/wiki/ISO_8601).
   * @return updatedAt
  **/
  @ApiModelProperty(example = "2011-12-03T10:15:30Z", required = true, value = "Provided in [ISO 8601 format](link: https://en.wikipedia.org/wiki/ISO_8601).")

  public String getUpdatedAt() {
    return updatedAt;
  }



  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public BadgeApplication campaign(BadgeApplicationCampaign campaign) {
    
    this.campaign = campaign;
    return this;
  }

   /**
   * Get campaign
   * @return campaign
  **/
  @ApiModelProperty(required = true, value = "")

  public BadgeApplicationCampaign getCampaign() {
    return campaign;
  }



  public void setCampaign(BadgeApplicationCampaign campaign) {
    this.campaign = campaign;
  }


  public BadgeApplication offer(BadgeApplicationOffer offer) {
    
    this.offer = offer;
    return this;
  }

   /**
   * Get offer
   * @return offer
  **/
  @ApiModelProperty(required = true, value = "")

  public BadgeApplicationOffer getOffer() {
    return offer;
  }



  public void setOffer(BadgeApplicationOffer offer) {
    this.offer = offer;
  }


  public BadgeApplication prices(BadgeApplicationPrices prices) {
    
    this.prices = prices;
    return this;
  }

   /**
   * Get prices
   * @return prices
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BadgeApplicationPrices getPrices() {
    return prices;
  }



  public void setPrices(BadgeApplicationPrices prices) {
    this.prices = prices;
  }


  public BadgeApplication process(BadgeApplicationProcess process) {
    
    this.process = process;
    return this;
  }

   /**
   * Get process
   * @return process
  **/
  @ApiModelProperty(required = true, value = "")

  public BadgeApplicationProcess getProcess() {
    return process;
  }



  public void setProcess(BadgeApplicationProcess process) {
    this.process = process;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BadgeApplication badgeApplication = (BadgeApplication) o;
    return Objects.equals(this.id, badgeApplication.id) &&
        Objects.equals(this.createdAt, badgeApplication.createdAt) &&
        Objects.equals(this.updatedAt, badgeApplication.updatedAt) &&
        Objects.equals(this.campaign, badgeApplication.campaign) &&
        Objects.equals(this.offer, badgeApplication.offer) &&
        Objects.equals(this.prices, badgeApplication.prices) &&
        Objects.equals(this.process, badgeApplication.process);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, updatedAt, campaign, offer, prices, process);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BadgeApplication {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    campaign: ").append(toIndentedString(campaign)).append("\n");
    sb.append("    offer: ").append(toIndentedString(offer)).append("\n");
    sb.append("    prices: ").append(toIndentedString(prices)).append("\n");
    sb.append("    process: ").append(toIndentedString(process)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

