/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * BlackListPagedResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class BlackListPagedResponse {
  public static final String SERIALIZED_NAME_BLACKLISTED_USERS = "blacklistedUsers";
  @SerializedName(SERIALIZED_NAME_BLACKLISTED_USERS)
  private List<BlackListResponse> blacklistedUsers = null;

  public static final String SERIALIZED_NAME_OFFSET = "offset";
  @SerializedName(SERIALIZED_NAME_OFFSET)
  private Integer offset;

  public static final String SERIALIZED_NAME_LIMIT = "limit";
  @SerializedName(SERIALIZED_NAME_LIMIT)
  private Integer limit;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private Integer total;


  public BlackListPagedResponse blacklistedUsers(List<BlackListResponse> blacklistedUsers) {
    
    this.blacklistedUsers = blacklistedUsers;
    return this;
  }

  public BlackListPagedResponse addBlacklistedUsersItem(BlackListResponse blacklistedUsersItem) {
    if (this.blacklistedUsers == null) {
      this.blacklistedUsers = new ArrayList<BlackListResponse>();
    }
    this.blacklistedUsers.add(blacklistedUsersItem);
    return this;
  }

   /**
   * Get blacklistedUsers
   * @return blacklistedUsers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<BlackListResponse> getBlacklistedUsers() {
    return blacklistedUsers;
  }



  public void setBlacklistedUsers(List<BlackListResponse> blacklistedUsers) {
    this.blacklistedUsers = blacklistedUsers;
  }


  public BlackListPagedResponse offset(Integer offset) {
    
    this.offset = offset;
    return this;
  }

   /**
   * Get offset
   * @return offset
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getOffset() {
    return offset;
  }



  public void setOffset(Integer offset) {
    this.offset = offset;
  }


  public BlackListPagedResponse limit(Integer limit) {
    
    this.limit = limit;
    return this;
  }

   /**
   * Get limit
   * @return limit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getLimit() {
    return limit;
  }



  public void setLimit(Integer limit) {
    this.limit = limit;
  }


  public BlackListPagedResponse total(Integer total) {
    
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTotal() {
    return total;
  }



  public void setTotal(Integer total) {
    this.total = total;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlackListPagedResponse blackListPagedResponse = (BlackListPagedResponse) o;
    return Objects.equals(this.blacklistedUsers, blackListPagedResponse.blacklistedUsers) &&
        Objects.equals(this.offset, blackListPagedResponse.offset) &&
        Objects.equals(this.limit, blackListPagedResponse.limit) &&
        Objects.equals(this.total, blackListPagedResponse.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(blacklistedUsers, offset, limit, total);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlackListPagedResponse {\n");
    sb.append("    blacklistedUsers: ").append(toIndentedString(blacklistedUsers)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

