/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * The buyer&#39;s data.
 */
@ApiModel(description = "The buyer's data.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class BuyerParticipant {
  public static final String SERIALIZED_NAME_COMPANY_NAME = "companyName";
  @SerializedName(SERIALIZED_NAME_COMPANY_NAME)
  private String companyName;

  public static final String SERIALIZED_NAME_LOGIN = "login";
  @SerializedName(SERIALIZED_NAME_LOGIN)
  private String login;

  public static final String SERIALIZED_NAME_FIRST_NAME = "firstName";
  @SerializedName(SERIALIZED_NAME_FIRST_NAME)
  private String firstName;

  public static final String SERIALIZED_NAME_LAST_NAME = "lastName";
  @SerializedName(SERIALIZED_NAME_LAST_NAME)
  private String lastName;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private OperationParticipantAddress address;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;


  public BuyerParticipant companyName(String companyName) {
    
    this.companyName = companyName;
    return this;
  }

   /**
   * Company name.
   * @return companyName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Allegro", value = "Company name.")

  public String getCompanyName() {
    return companyName;
  }



  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }


  public BuyerParticipant login(String login) {
    
    this.login = login;
    return this;
  }

   /**
   * Login.
   * @return login
  **/
  @ApiModelProperty(example = "User_login", required = true, value = "Login.")

  public String getLogin() {
    return login;
  }



  public void setLogin(String login) {
    this.login = login;
  }


  public BuyerParticipant firstName(String firstName) {
    
    this.firstName = firstName;
    return this;
  }

   /**
   * First name.
   * @return firstName
  **/
  @ApiModelProperty(example = "Jan", required = true, value = "First name.")

  public String getFirstName() {
    return firstName;
  }



  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }


  public BuyerParticipant lastName(String lastName) {
    
    this.lastName = lastName;
    return this;
  }

   /**
   * Last name.
   * @return lastName
  **/
  @ApiModelProperty(example = "Nowak", required = true, value = "Last name.")

  public String getLastName() {
    return lastName;
  }



  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  public BuyerParticipant address(OperationParticipantAddress address) {
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OperationParticipantAddress getAddress() {
    return address;
  }



  public void setAddress(OperationParticipantAddress address) {
    this.address = address;
  }


  public BuyerParticipant id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The buyers&#39;s ID.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "The buyers's ID.")

  public String getId() {
    return id;
  }



  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BuyerParticipant buyerParticipant = (BuyerParticipant) o;
    return Objects.equals(this.companyName, buyerParticipant.companyName) &&
        Objects.equals(this.login, buyerParticipant.login) &&
        Objects.equals(this.firstName, buyerParticipant.firstName) &&
        Objects.equals(this.lastName, buyerParticipant.lastName) &&
        Objects.equals(this.address, buyerParticipant.address) &&
        Objects.equals(this.id, buyerParticipant.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyName, login, firstName, lastName, address, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BuyerParticipant {\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    login: ").append(toIndentedString(login)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

