/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * CheckoutForms
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class CheckoutForms {
  public static final String SERIALIZED_NAME_CHECKOUT_FORMS = "checkoutForms";
  @SerializedName(SERIALIZED_NAME_CHECKOUT_FORMS)
  private List<CheckoutForm> checkoutForms = new ArrayList<CheckoutForm>();

  public static final String SERIALIZED_NAME_COUNT = "count";
  @SerializedName(SERIALIZED_NAME_COUNT)
  private BigDecimal count;

  public static final String SERIALIZED_NAME_TOTAL_COUNT = "totalCount";
  @SerializedName(SERIALIZED_NAME_TOTAL_COUNT)
  private BigDecimal totalCount;


  public CheckoutForms checkoutForms(List<CheckoutForm> checkoutForms) {
    
    this.checkoutForms = checkoutForms;
    return this;
  }

  public CheckoutForms addCheckoutFormsItem(CheckoutForm checkoutFormsItem) {
    this.checkoutForms.add(checkoutFormsItem);
    return this;
  }

   /**
   * Get checkoutForms
   * @return checkoutForms
  **/
  @ApiModelProperty(required = true, value = "")

  public List<CheckoutForm> getCheckoutForms() {
    return checkoutForms;
  }



  public void setCheckoutForms(List<CheckoutForm> checkoutForms) {
    this.checkoutForms = checkoutForms;
  }


  public CheckoutForms count(BigDecimal count) {
    
    this.count = count;
    return this;
  }

   /**
   * number of returned objects
   * @return count
  **/
  @ApiModelProperty(example = "1", required = true, value = "number of returned objects")

  public BigDecimal getCount() {
    return count;
  }



  public void setCount(BigDecimal count) {
    this.count = count;
  }


  public CheckoutForms totalCount(BigDecimal totalCount) {
    
    this.totalCount = totalCount;
    return this;
  }

   /**
   * Number of all objects of requested status(es) available (regardless of the provided limit and offset) 
   * @return totalCount
  **/
  @ApiModelProperty(example = "1", required = true, value = "Number of all objects of requested status(es) available (regardless of the provided limit and offset) ")

  public BigDecimal getTotalCount() {
    return totalCount;
  }



  public void setTotalCount(BigDecimal totalCount) {
    this.totalCount = totalCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckoutForms checkoutForms = (CheckoutForms) o;
    return Objects.equals(this.checkoutForms, checkoutForms.checkoutForms) &&
        Objects.equals(this.count, checkoutForms.count) &&
        Objects.equals(this.totalCount, checkoutForms.totalCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(checkoutForms, count, totalCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckoutForms {\n");
    sb.append("    checkoutForms: ").append(toIndentedString(checkoutForms)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

