/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

/**
 * Guaranteed date when first delivery attempt takes place. This is always filled for X-press Couriers delivery method.
 */
@ApiModel(description = "Guaranteed date when first delivery attempt takes place. This is always filled for X-press Couriers delivery method.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class CheckoutFormDeliveryTimeGuaranteed {
  public static final String SERIALIZED_NAME_FROM = "from";
  @SerializedName(SERIALIZED_NAME_FROM)
  private OffsetDateTime from;

  public static final String SERIALIZED_NAME_TO = "to";
  @SerializedName(SERIALIZED_NAME_TO)
  private OffsetDateTime to;


  public CheckoutFormDeliveryTimeGuaranteed from(OffsetDateTime from) {
    
    this.from = from;
    return this;
  }

   /**
   * ISO date when the earliest delivery attempt can take place.
   * @return from
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2018-01-01T16:00Z", value = "ISO date when the earliest delivery attempt can take place.")

  public OffsetDateTime getFrom() {
    return from;
  }



  public void setFrom(OffsetDateTime from) {
    this.from = from;
  }


  public CheckoutFormDeliveryTimeGuaranteed to(OffsetDateTime to) {
    
    this.to = to;
    return this;
  }

   /**
   * ISO date when the latest delivery attempt can take place.
   * @return to
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2018-01-01T18:00Z", value = "ISO date when the latest delivery attempt can take place.")

  public OffsetDateTime getTo() {
    return to;
  }



  public void setTo(OffsetDateTime to) {
    this.to = to;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckoutFormDeliveryTimeGuaranteed checkoutFormDeliveryTimeGuaranteed = (CheckoutFormDeliveryTimeGuaranteed) o;
    return Objects.equals(this.from, checkoutFormDeliveryTimeGuaranteed.from) &&
        Objects.equals(this.to, checkoutFormDeliveryTimeGuaranteed.to);
  }

  @Override
  public int hashCode() {
    return Objects.hash(from, to);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckoutFormDeliveryTimeGuaranteed {\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

