/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * CompatibleProductsGroupsDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class CompatibleProductsGroupsDto {
  public static final String SERIALIZED_NAME_GROUPS = "groups";
  @SerializedName(SERIALIZED_NAME_GROUPS)
  private List<CompatibleProductsGroupsDtoGroups> groups = null;

  public static final String SERIALIZED_NAME_COUNT = "count";
  @SerializedName(SERIALIZED_NAME_COUNT)
  private Integer count;

  public static final String SERIALIZED_NAME_TOTAL_COUNT = "totalCount";
  @SerializedName(SERIALIZED_NAME_TOTAL_COUNT)
  private Integer totalCount;


  public CompatibleProductsGroupsDto groups(List<CompatibleProductsGroupsDtoGroups> groups) {
    
    this.groups = groups;
    return this;
  }

  public CompatibleProductsGroupsDto addGroupsItem(CompatibleProductsGroupsDtoGroups groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<CompatibleProductsGroupsDtoGroups>();
    }
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * List of groups for given type of compatible products.
   * @return groups
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[{\"id\":\"b0dfe6de8fb2f2b1309ad94c6cc4e09d\",\"text\":\"ABARTH\"},{\"id\":\"4144e097d2fa7a491cec2a7a4322f2bc\",\"text\":\"AC\"},{\"id\":\"de3e2253f276cd1c757f58860d77b9bb\",\"text\":\"ACURA\"}]", value = "List of groups for given type of compatible products.")

  public List<CompatibleProductsGroupsDtoGroups> getGroups() {
    return groups;
  }



  public void setGroups(List<CompatibleProductsGroupsDtoGroups> groups) {
    this.groups = groups;
  }


  public CompatibleProductsGroupsDto count(Integer count) {
    
    this.count = count;
    return this;
  }

   /**
   * Number of returned elements.
   * @return count
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "3", value = "Number of returned elements.")

  public Integer getCount() {
    return count;
  }



  public void setCount(Integer count) {
    this.count = count;
  }


  public CompatibleProductsGroupsDto totalCount(Integer totalCount) {
    
    this.totalCount = totalCount;
    return this;
  }

   /**
   * Total number of available elements.
   * @return totalCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "256", value = "Total number of available elements.")

  public Integer getTotalCount() {
    return totalCount;
  }



  public void setTotalCount(Integer totalCount) {
    this.totalCount = totalCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompatibleProductsGroupsDto compatibleProductsGroupsDto = (CompatibleProductsGroupsDto) o;
    return Objects.equals(this.groups, compatibleProductsGroupsDto.groups) &&
        Objects.equals(this.count, compatibleProductsGroupsDto.count) &&
        Objects.equals(this.totalCount, compatibleProductsGroupsDto.totalCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groups, count, totalCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompatibleProductsGroupsDto {\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

