/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Contains fields to change
 */
@ApiModel(description = "Contains fields to change")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class Modification {
  public static final String SERIALIZED_NAME_ADDITIONAL_SERVICES_GROUP = "additionalServicesGroup";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_SERVICES_GROUP)
  private AdditionalServicesGroup additionalServicesGroup;

  public static final String SERIALIZED_NAME_DELIVERY = "delivery";
  @SerializedName(SERIALIZED_NAME_DELIVERY)
  private ModificationDelivery delivery;

  public static final String SERIALIZED_NAME_PAYMENTS = "payments";
  @SerializedName(SERIALIZED_NAME_PAYMENTS)
  private ModificationPayments payments;

  public static final String SERIALIZED_NAME_PROMOTION = "promotion";
  @SerializedName(SERIALIZED_NAME_PROMOTION)
  private ModificationPromotion promotion;

  public static final String SERIALIZED_NAME_SIZE_TABLE = "sizeTable";
  @SerializedName(SERIALIZED_NAME_SIZE_TABLE)
  private ModificationSizeTable sizeTable;

  public static final String SERIALIZED_NAME_PUBLICATION = "publication";
  @SerializedName(SERIALIZED_NAME_PUBLICATION)
  private ModificationPublication publication;


  public Modification additionalServicesGroup(AdditionalServicesGroup additionalServicesGroup) {
    
    this.additionalServicesGroup = additionalServicesGroup;
    return this;
  }

   /**
   * Get additionalServicesGroup
   * @return additionalServicesGroup
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AdditionalServicesGroup getAdditionalServicesGroup() {
    return additionalServicesGroup;
  }



  public void setAdditionalServicesGroup(AdditionalServicesGroup additionalServicesGroup) {
    this.additionalServicesGroup = additionalServicesGroup;
  }


  public Modification delivery(ModificationDelivery delivery) {
    
    this.delivery = delivery;
    return this;
  }

   /**
   * Get delivery
   * @return delivery
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ModificationDelivery getDelivery() {
    return delivery;
  }



  public void setDelivery(ModificationDelivery delivery) {
    this.delivery = delivery;
  }


  public Modification payments(ModificationPayments payments) {
    
    this.payments = payments;
    return this;
  }

   /**
   * Get payments
   * @return payments
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ModificationPayments getPayments() {
    return payments;
  }



  public void setPayments(ModificationPayments payments) {
    this.payments = payments;
  }


  public Modification promotion(ModificationPromotion promotion) {
    
    this.promotion = promotion;
    return this;
  }

   /**
   * Get promotion
   * @return promotion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ModificationPromotion getPromotion() {
    return promotion;
  }



  public void setPromotion(ModificationPromotion promotion) {
    this.promotion = promotion;
  }


  public Modification sizeTable(ModificationSizeTable sizeTable) {
    
    this.sizeTable = sizeTable;
    return this;
  }

   /**
   * Get sizeTable
   * @return sizeTable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ModificationSizeTable getSizeTable() {
    return sizeTable;
  }



  public void setSizeTable(ModificationSizeTable sizeTable) {
    this.sizeTable = sizeTable;
  }


  public Modification publication(ModificationPublication publication) {
    
    this.publication = publication;
    return this;
  }

   /**
   * Get publication
   * @return publication
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ModificationPublication getPublication() {
    return publication;
  }



  public void setPublication(ModificationPublication publication) {
    this.publication = publication;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Modification modification = (Modification) o;
    return Objects.equals(this.additionalServicesGroup, modification.additionalServicesGroup) &&
        Objects.equals(this.delivery, modification.delivery) &&
        Objects.equals(this.payments, modification.payments) &&
        Objects.equals(this.promotion, modification.promotion) &&
        Objects.equals(this.sizeTable, modification.sizeTable) &&
        Objects.equals(this.publication, modification.publication);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additionalServicesGroup, delivery, payments, promotion, sizeTable, publication);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Modification {\n");
    sb.append("    additionalServicesGroup: ").append(toIndentedString(additionalServicesGroup)).append("\n");
    sb.append("    delivery: ").append(toIndentedString(delivery)).append("\n");
    sb.append("    payments: ").append(toIndentedString(payments)).append("\n");
    sb.append("    promotion: ").append(toIndentedString(promotion)).append("\n");
    sb.append("    sizeTable: ").append(toIndentedString(sizeTable)).append("\n");
    sb.append("    publication: ").append(toIndentedString(publication)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

