/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Information on the offer&#39;s publication status and dates.
 */
@ApiModel(description = "Information on the offer's publication status and dates.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class OfferListingDtoV1Publication {
  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private OfferStatus status;

  public static final String SERIALIZED_NAME_STARTING_AT = "startingAt";
  @SerializedName(SERIALIZED_NAME_STARTING_AT)
  private String startingAt;

  public static final String SERIALIZED_NAME_STARTED_AT = "startedAt";
  @SerializedName(SERIALIZED_NAME_STARTED_AT)
  private String startedAt;

  public static final String SERIALIZED_NAME_ENDING_AT = "endingAt";
  @SerializedName(SERIALIZED_NAME_ENDING_AT)
  private String endingAt;

  public static final String SERIALIZED_NAME_ENDED_AT = "endedAt";
  @SerializedName(SERIALIZED_NAME_ENDED_AT)
  private String endedAt;


  public OfferListingDtoV1Publication status(OfferStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OfferStatus getStatus() {
    return status;
  }



  public void setStatus(OfferStatus status) {
    this.status = status;
  }


  public OfferListingDtoV1Publication startingAt(String startingAt) {
    
    this.startingAt = startingAt;
    return this;
  }

   /**
   * The date and time of activation in UTC for a planned listing.
   * @return startingAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2019-05-29T12:00:00Z", value = "The date and time of activation in UTC for a planned listing.")

  public String getStartingAt() {
    return startingAt;
  }



  public void setStartingAt(String startingAt) {
    this.startingAt = startingAt;
  }


  public OfferListingDtoV1Publication startedAt(String startedAt) {
    
    this.startedAt = startedAt;
    return this;
  }

   /**
   * The actual date and time of activation in UTC.
   * @return startedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2019-05-29T12:00:00Z", value = "The actual date and time of activation in UTC.")

  public String getStartedAt() {
    return startedAt;
  }



  public void setStartedAt(String startedAt) {
    this.startedAt = startedAt;
  }


  public OfferListingDtoV1Publication endingAt(String endingAt) {
    
    this.endingAt = endingAt;
    return this;
  }

   /**
   * The date and time of a planned ending in UTC.
   * @return endingAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2019-06-30T12:00:00Z", value = "The date and time of a planned ending in UTC.")

  public String getEndingAt() {
    return endingAt;
  }



  public void setEndingAt(String endingAt) {
    this.endingAt = endingAt;
  }


  public OfferListingDtoV1Publication endedAt(String endedAt) {
    
    this.endedAt = endedAt;
    return this;
  }

   /**
   * The actual date and time of last ending in UTC.
   * @return endedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2019-06-30T12:10:00Z", value = "The actual date and time of last ending in UTC.")

  public String getEndedAt() {
    return endedAt;
  }



  public void setEndedAt(String endedAt) {
    this.endedAt = endedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OfferListingDtoV1Publication offerListingDtoV1Publication = (OfferListingDtoV1Publication) o;
    return Objects.equals(this.status, offerListingDtoV1Publication.status) &&
        Objects.equals(this.startingAt, offerListingDtoV1Publication.startingAt) &&
        Objects.equals(this.startedAt, offerListingDtoV1Publication.startedAt) &&
        Objects.equals(this.endingAt, offerListingDtoV1Publication.endingAt) &&
        Objects.equals(this.endedAt, offerListingDtoV1Publication.endedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, startingAt, startedAt, endingAt, endedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OfferListingDtoV1Publication {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    startingAt: ").append(toIndentedString(startingAt)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    endingAt: ").append(toIndentedString(endingAt)).append("\n");
    sb.append("    endedAt: ").append(toIndentedString(endedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

