/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;
import java.util.UUID;

/**
 * PaymentIdMapping
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class PaymentIdMapping {
  public static final String SERIALIZED_NAME_PAYMENT_ID = "paymentId";
  @SerializedName(SERIALIZED_NAME_PAYMENT_ID)
  private UUID paymentId;

  public static final String SERIALIZED_NAME_TRANSACTION_ID = "transactionId";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_ID)
  private String transactionId;


  public PaymentIdMapping paymentId(UUID paymentId) {
    
    this.paymentId = paymentId;
    return this;
  }

   /**
   * The payment ID compatible with RestAPI.
   * @return paymentId
  **/
  @ApiModelProperty(example = "2e2fe432-2115-32f9-82ae-e350e7aa9ed0", required = true, value = "The payment ID compatible with RestAPI.")

  public UUID getPaymentId() {
    return paymentId;
  }



  public void setPaymentId(UUID paymentId) {
    this.paymentId = paymentId;
  }


  public PaymentIdMapping transactionId(String transactionId) {
    
    this.transactionId = transactionId;
    return this;
  }

   /**
   * The transaction ID compatible with WebAPI.
   * @return transactionId
  **/
  @ApiModelProperty(example = "1016873349", required = true, value = "The transaction ID compatible with WebAPI.")

  public String getTransactionId() {
    return transactionId;
  }



  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentIdMapping paymentIdMapping = (PaymentIdMapping) o;
    return Objects.equals(this.paymentId, paymentIdMapping.paymentId) &&
        Objects.equals(this.transactionId, paymentIdMapping.transactionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentId, transactionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentIdMapping {\n");
    sb.append("    paymentId: ").append(toIndentedString(paymentId)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

