/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Pos
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class Pos {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_EXTERNAL_ID = "externalId";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_ID)
  private String externalId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_SELLER = "seller";
  @SerializedName(SERIALIZED_NAME_SELLER)
  private Seller seller;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private Address address;

  public static final String SERIALIZED_NAME_PHONE_NUMBER = "phoneNumber";
  @SerializedName(SERIALIZED_NAME_PHONE_NUMBER)
  private String phoneNumber;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_OPEN_HOURS = "openHours";
  @SerializedName(SERIALIZED_NAME_OPEN_HOURS)
  private List<OpenHour> openHours = new ArrayList<OpenHour>();

  public static final String SERIALIZED_NAME_SERVICE_TIME = "serviceTime";
  @SerializedName(SERIALIZED_NAME_SERVICE_TIME)
  private String serviceTime;

  public static final String SERIALIZED_NAME_PAYMENTS = "payments";
  @SerializedName(SERIALIZED_NAME_PAYMENTS)
  private List<Payment> payments = null;

  public static final String SERIALIZED_NAME_CONFIRMATION_TYPE = "confirmationType";
  @SerializedName(SERIALIZED_NAME_CONFIRMATION_TYPE)
  private String confirmationType;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;


  public Pos id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * UUID. When creating a point of service (Post) the field is ignored. It is required when updating (Put) a point of service.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "UUID. When creating a point of service (Post) the field is ignored. It is required when updating (Put) a point of service.")

  public String getId() {
    return id;
  }



  public void setId(String id) {
    this.id = id;
  }


  public Pos externalId(String externalId) {
    
    this.externalId = externalId;
    return this;
  }

   /**
   * ID from external client system.
   * @return externalId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ID from external client system.")

  public String getExternalId() {
    return externalId;
  }



  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }


  public Pos name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }



  public void setName(String name) {
    this.name = name;
  }


  public Pos seller(Seller seller) {
    
    this.seller = seller;
    return this;
  }

   /**
   * Get seller
   * @return seller
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Seller getSeller() {
    return seller;
  }



  public void setSeller(Seller seller) {
    this.seller = seller;
  }


  public Pos type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Indicates point type. The only valid value so far is PICKUP_POINT.
   * @return type
  **/
  @ApiModelProperty(required = true, value = "Indicates point type. The only valid value so far is PICKUP_POINT.")

  public String getType() {
    return type;
  }



  public void setType(String type) {
    this.type = type;
  }


  public Pos address(Address address) {
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(required = true, value = "")

  public Address getAddress() {
    return address;
  }



  public void setAddress(Address address) {
    this.address = address;
  }


  public Pos phoneNumber(String phoneNumber) {
    
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Get phoneNumber
   * @return phoneNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPhoneNumber() {
    return phoneNumber;
  }



  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  public Pos email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEmail() {
    return email;
  }



  public void setEmail(String email) {
    this.email = email;
  }


  public Pos openHours(List<OpenHour> openHours) {
    
    this.openHours = openHours;
    return this;
  }

  public Pos addOpenHoursItem(OpenHour openHoursItem) {
    this.openHours.add(openHoursItem);
    return this;
  }

   /**
   * Possible empty list of opening hours.
   * @return openHours
  **/
  @ApiModelProperty(required = true, value = "Possible empty list of opening hours.")

  public List<OpenHour> getOpenHours() {
    return openHours;
  }



  public void setOpenHours(List<OpenHour> openHours) {
    this.openHours = openHours;
  }


  public Pos serviceTime(String serviceTime) {
    
    this.serviceTime = serviceTime;
    return this;
  }

   /**
   * Delivery time / Time period for receipt. Date format ISO 8601 e.g. &#39;PT24H&#39;
   * @return serviceTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Delivery time / Time period for receipt. Date format ISO 8601 e.g. 'PT24H'")

  public String getServiceTime() {
    return serviceTime;
  }



  public void setServiceTime(String serviceTime) {
    this.serviceTime = serviceTime;
  }


  public Pos payments(List<Payment> payments) {
    
    this.payments = payments;
    return this;
  }

  public Pos addPaymentsItem(Payment paymentsItem) {
    if (this.payments == null) {
      this.payments = new ArrayList<Payment>();
    }
    this.payments.add(paymentsItem);
    return this;
  }

   /**
   * An empty list of payment types is available.
   * @return payments
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An empty list of payment types is available.")

  public List<Payment> getPayments() {
    return payments;
  }



  public void setPayments(List<Payment> payments) {
    this.payments = payments;
  }


  public Pos confirmationType(String confirmationType) {
    
    this.confirmationType = confirmationType;
    return this;
  }

   /**
   * Confirmation method: AWAIT_CONTACT - We will inform you about the time of receipt, CALL_US - Please make an appointment, CONTACT_NOT_REQUIRED - Contact is not required.
   * @return confirmationType
  **/
  @ApiModelProperty(required = true, value = "Confirmation method: AWAIT_CONTACT - We will inform you about the time of receipt, CALL_US - Please make an appointment, CONTACT_NOT_REQUIRED - Contact is not required.")

  public String getConfirmationType() {
    return confirmationType;
  }



  public void setConfirmationType(String confirmationType) {
    this.confirmationType = confirmationType;
  }


  public Pos status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Point of service status: ACTIVE - active, TEMPORARILY_CLOSED - temporarily closed, CLOSED_DOWN - closed down, DELETED - deleted.
   * @return status
  **/
  @ApiModelProperty(required = true, value = "Point of service status: ACTIVE - active, TEMPORARILY_CLOSED - temporarily closed, CLOSED_DOWN - closed down, DELETED - deleted.")

  public String getStatus() {
    return status;
  }



  public void setStatus(String status) {
    this.status = status;
  }


  public Pos createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Creation date. Date format (ISO 8601) - yyyy-MM-dd&#39;T&#39;HH:mm:ss.SSSZ When creating (Post) or updating (Put) a point of service (Post) the field is ignored.
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Creation date. Date format (ISO 8601) - yyyy-MM-dd'T'HH:mm:ss.SSSZ When creating (Post) or updating (Put) a point of service (Post) the field is ignored.")

  public String getCreatedAt() {
    return createdAt;
  }



  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public Pos updatedAt(String updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Modification date. Date format (ISO 8601) - yyyy-MM-dd&#39;T&#39;HH:mm:ss.SSSZ When creating (Post) or updating (Put) a point of service (Post) the field is ignored.
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Modification date. Date format (ISO 8601) - yyyy-MM-dd'T'HH:mm:ss.SSSZ When creating (Post) or updating (Put) a point of service (Post) the field is ignored.")

  public String getUpdatedAt() {
    return updatedAt;
  }



  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pos pos = (Pos) o;
    return Objects.equals(this.id, pos.id) &&
        Objects.equals(this.externalId, pos.externalId) &&
        Objects.equals(this.name, pos.name) &&
        Objects.equals(this.seller, pos.seller) &&
        Objects.equals(this.type, pos.type) &&
        Objects.equals(this.address, pos.address) &&
        Objects.equals(this.phoneNumber, pos.phoneNumber) &&
        Objects.equals(this.email, pos.email) &&
        Objects.equals(this.openHours, pos.openHours) &&
        Objects.equals(this.serviceTime, pos.serviceTime) &&
        Objects.equals(this.payments, pos.payments) &&
        Objects.equals(this.confirmationType, pos.confirmationType) &&
        Objects.equals(this.status, pos.status) &&
        Objects.equals(this.createdAt, pos.createdAt) &&
        Objects.equals(this.updatedAt, pos.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, externalId, name, seller, type, address, phoneNumber, email, openHours, serviceTime, payments, confirmationType, status, createdAt, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pos {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    seller: ").append(toIndentedString(seller)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    openHours: ").append(toIndentedString(openHours)).append("\n");
    sb.append("    serviceTime: ").append(toIndentedString(serviceTime)).append("\n");
    sb.append("    payments: ").append(toIndentedString(payments)).append("\n");
    sb.append("    confirmationType: ").append(toIndentedString(confirmationType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

