/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * SellerCreateRebateRequestDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class SellerCreateRebateRequestDto {
  public static final String SERIALIZED_NAME_BENEFITS = "benefits";
  @SerializedName(SERIALIZED_NAME_BENEFITS)
  private List<Benefit> benefits = new ArrayList<Benefit>();

  public static final String SERIALIZED_NAME_OFFER_CRITERIA = "offerCriteria";
  @SerializedName(SERIALIZED_NAME_OFFER_CRITERIA)
  private List<SellerRebateOfferCriterion> offerCriteria = new ArrayList<SellerRebateOfferCriterion>();


  public SellerCreateRebateRequestDto benefits(List<Benefit> benefits) {
    
    this.benefits = benefits;
    return this;
  }

  public SellerCreateRebateRequestDto addBenefitsItem(Benefit benefitsItem) {
    this.benefits.add(benefitsItem);
    return this;
  }

   /**
   * What kind of rebate will be given
   * @return benefits
  **/
  @ApiModelProperty(required = true, value = "What kind of rebate will be given")

  public List<Benefit> getBenefits() {
    return benefits;
  }



  public void setBenefits(List<Benefit> benefits) {
    this.benefits = benefits;
  }


  public SellerCreateRebateRequestDto offerCriteria(List<SellerRebateOfferCriterion> offerCriteria) {
    
    this.offerCriteria = offerCriteria;
    return this;
  }

  public SellerCreateRebateRequestDto addOfferCriteriaItem(SellerRebateOfferCriterion offerCriteriaItem) {
    this.offerCriteria.add(offerCriteriaItem);
    return this;
  }

   /**
   * What offers will be included
   * @return offerCriteria
  **/
  @ApiModelProperty(required = true, value = "What offers will be included")

  public List<SellerRebateOfferCriterion> getOfferCriteria() {
    return offerCriteria;
  }



  public void setOfferCriteria(List<SellerRebateOfferCriterion> offerCriteria) {
    this.offerCriteria = offerCriteria;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SellerCreateRebateRequestDto sellerCreateRebateRequestDto = (SellerCreateRebateRequestDto) o;
    return Objects.equals(this.benefits, sellerCreateRebateRequestDto.benefits) &&
        Objects.equals(this.offerCriteria, sellerCreateRebateRequestDto.offerCriteria);
  }

  @Override
  public int hashCode() {
    return Objects.hash(benefits, offerCriteria);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SellerCreateRebateRequestDto {\n");
    sb.append("    benefits: ").append(toIndentedString(benefits)).append("\n");
    sb.append("    offerCriteria: ").append(toIndentedString(offerCriteria)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

