/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Offers updates summary
 */
@ApiModel(description = "Offers updates summary")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class TaskCount {
  public static final String SERIALIZED_NAME_FAILED = "failed";
  @SerializedName(SERIALIZED_NAME_FAILED)
  private Integer failed;

  public static final String SERIALIZED_NAME_SUCCESS = "success";
  @SerializedName(SERIALIZED_NAME_SUCCESS)
  private Integer success;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private Integer total;


  public TaskCount failed(Integer failed) {
    
    this.failed = failed;
    return this;
  }

   /**
   * Current number of failed offers updates
   * @return failed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Current number of failed offers updates")

  public Integer getFailed() {
    return failed;
  }



  public void setFailed(Integer failed) {
    this.failed = failed;
  }


  public TaskCount success(Integer success) {
    
    this.success = success;
    return this;
  }

   /**
   * Current number of success offers updates
   * @return success
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Current number of success offers updates")

  public Integer getSuccess() {
    return success;
  }



  public void setSuccess(Integer success) {
    this.success = success;
  }


  public TaskCount total(Integer total) {
    
    this.total = total;
    return this;
  }

   /**
   * Total number of scheduled offers updates
   * @return total
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total number of scheduled offers updates")

  public Integer getTotal() {
    return total;
  }



  public void setTotal(Integer total) {
    this.total = total;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaskCount taskCount = (TaskCount) o;
    return Objects.equals(this.failed, taskCount.failed) &&
        Objects.equals(this.success, taskCount.success) &&
        Objects.equals(this.total, taskCount.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(failed, success, total);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskCount {\n");
    sb.append("    failed: ").append(toIndentedString(failed)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

