/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.service.source.allegro.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * WrapsListingAndCommissionsFees
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class WrapsListingAndCommissionsFees {
  public static final String SERIALIZED_NAME_COMMISSIONS = "commissions";
  @SerializedName(SERIALIZED_NAME_COMMISSIONS)
  private List<DescribesSuccessCommissionFee> commissions = new ArrayList<DescribesSuccessCommissionFee>();

  public static final String SERIALIZED_NAME_QUOTES = "quotes";
  @SerializedName(SERIALIZED_NAME_QUOTES)
  private List<DescribesListingFee> quotes = new ArrayList<DescribesListingFee>();


  public WrapsListingAndCommissionsFees commissions(List<DescribesSuccessCommissionFee> commissions) {
    
    this.commissions = commissions;
    return this;
  }

  public WrapsListingAndCommissionsFees addCommissionsItem(DescribesSuccessCommissionFee commissionsItem) {
    this.commissions.add(commissionsItem);
    return this;
  }

   /**
   * Get commissions
   * @return commissions
  **/
  @ApiModelProperty(required = true, value = "")

  public List<DescribesSuccessCommissionFee> getCommissions() {
    return commissions;
  }



  public void setCommissions(List<DescribesSuccessCommissionFee> commissions) {
    this.commissions = commissions;
  }


  public WrapsListingAndCommissionsFees quotes(List<DescribesListingFee> quotes) {
    
    this.quotes = quotes;
    return this;
  }

  public WrapsListingAndCommissionsFees addQuotesItem(DescribesListingFee quotesItem) {
    this.quotes.add(quotesItem);
    return this;
  }

   /**
   * Get quotes
   * @return quotes
  **/
  @ApiModelProperty(required = true, value = "")

  public List<DescribesListingFee> getQuotes() {
    return quotes;
  }



  public void setQuotes(List<DescribesListingFee> quotes) {
    this.quotes = quotes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WrapsListingAndCommissionsFees wrapsListingAndCommissionsFees = (WrapsListingAndCommissionsFees) o;
    return Objects.equals(this.commissions, wrapsListingAndCommissionsFees.commissions) &&
        Objects.equals(this.quotes, wrapsListingAndCommissionsFees.quotes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commissions, quotes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WrapsListingAndCommissionsFees {\n");
    sb.append("    commissions: ").append(toIndentedString(commissions)).append("\n");
    sb.append("    quotes: ").append(toIndentedString(quotes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

