/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * CategoryProductParameterList
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class CategoryProductParameterList {
  public static final String SERIALIZED_NAME_PARAMETERS = "parameters";
  @SerializedName(SERIALIZED_NAME_PARAMETERS)
  private List<CategoryProductParameter> parameters = null;


  public CategoryProductParameterList parameters(List<CategoryProductParameter> parameters) {
    
    this.parameters = parameters;
    return this;
  }

  public CategoryProductParameterList addParametersItem(CategoryProductParameter parametersItem) {
    if (this.parameters == null) {
      this.parameters = new ArrayList<CategoryProductParameter>();
    }
    this.parameters.add(parametersItem);
    return this;
  }

   /**
   * The list of product parameters supported by the category.
   * @return parameters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The list of product parameters supported by the category.")

  public List<CategoryProductParameter> getParameters() {
    return parameters;
  }



  public void setParameters(List<CategoryProductParameter> parameters) {
    this.parameters = parameters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CategoryProductParameterList categoryProductParameterList = (CategoryProductParameterList) o;
    return Objects.equals(this.parameters, categoryProductParameterList.parameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parameters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CategoryProductParameterList {\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

