/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * CheckoutFormSummary
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class CheckoutFormSummary {
  public static final String SERIALIZED_NAME_TOTAL_TO_PAY = "totalToPay";
  @SerializedName(SERIALIZED_NAME_TOTAL_TO_PAY)
  private Price totalToPay;


  public CheckoutFormSummary totalToPay(Price totalToPay) {
    
    this.totalToPay = totalToPay;
    return this;
  }

   /**
   * Get totalToPay
   * @return totalToPay
  **/
  @ApiModelProperty(required = true, value = "")

  public Price getTotalToPay() {
    return totalToPay;
  }



  public void setTotalToPay(Price totalToPay) {
    this.totalToPay = totalToPay;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckoutFormSummary checkoutFormSummary = (CheckoutFormSummary) o;
    return Objects.equals(this.totalToPay, checkoutFormSummary.totalToPay);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalToPay);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckoutFormSummary {\n");
    sb.append("    totalToPay: ").append(toIndentedString(totalToPay)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

