/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ClassifiedPackageConfig
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class ClassifiedPackageConfig {
  public static final String SERIALIZED_NAME_EXTENSIONS = "extensions";
  @SerializedName(SERIALIZED_NAME_EXTENSIONS)
  private List<ClassifiedExtension> extensions = null;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PROMOTIONS = "promotions";
  @SerializedName(SERIALIZED_NAME_PROMOTIONS)
  private List<ClassifiedPromotion> promotions = null;

  public static final String SERIALIZED_NAME_PUBLICATION = "publication";
  @SerializedName(SERIALIZED_NAME_PUBLICATION)
  private ClassifiedPublication publication;

  /**
   * Gets or Sets type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    BASE("BASE"),
    
    EXTRA("EXTRA");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;


  public ClassifiedPackageConfig extensions(List<ClassifiedExtension> extensions) {
    
    this.extensions = extensions;
    return this;
  }

  public ClassifiedPackageConfig addExtensionsItem(ClassifiedExtension extensionsItem) {
    if (this.extensions == null) {
      this.extensions = new ArrayList<ClassifiedExtension>();
    }
    this.extensions.add(extensionsItem);
    return this;
  }

   /**
   * Get extensions
   * @return extensions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ClassifiedExtension> getExtensions() {
    return extensions;
  }



  public void setExtensions(List<ClassifiedExtension> extensions) {
    this.extensions = extensions;
  }


  public ClassifiedPackageConfig id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The classifieds package ID.
   * @return id
  **/
  @ApiModelProperty(example = "6174be19-56f9-484b-b72c-43b0b00785e8", required = true, value = "The classifieds package ID.")

  public String getId() {
    return id;
  }



  public void setId(String id) {
    this.id = id;
  }


  public ClassifiedPackageConfig name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The classifieds package name.
   * @return name
  **/
  @ApiModelProperty(example = "Power", required = true, value = "The classifieds package name.")

  public String getName() {
    return name;
  }



  public void setName(String name) {
    this.name = name;
  }


  public ClassifiedPackageConfig promotions(List<ClassifiedPromotion> promotions) {
    
    this.promotions = promotions;
    return this;
  }

  public ClassifiedPackageConfig addPromotionsItem(ClassifiedPromotion promotionsItem) {
    if (this.promotions == null) {
      this.promotions = new ArrayList<ClassifiedPromotion>();
    }
    this.promotions.add(promotionsItem);
    return this;
  }

   /**
   * A list of additional promotions included in the package.
   * @return promotions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of additional promotions included in the package.")

  public List<ClassifiedPromotion> getPromotions() {
    return promotions;
  }



  public void setPromotions(List<ClassifiedPromotion> promotions) {
    this.promotions = promotions;
  }


  public ClassifiedPackageConfig publication(ClassifiedPublication publication) {
    
    this.publication = publication;
    return this;
  }

   /**
   * Get publication
   * @return publication
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ClassifiedPublication getPublication() {
    return publication;
  }



  public void setPublication(ClassifiedPublication publication) {
    this.publication = publication;
  }


  public ClassifiedPackageConfig type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(required = true, value = "")

  public TypeEnum getType() {
    return type;
  }



  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClassifiedPackageConfig classifiedPackageConfig = (ClassifiedPackageConfig) o;
    return Objects.equals(this.extensions, classifiedPackageConfig.extensions) &&
        Objects.equals(this.id, classifiedPackageConfig.id) &&
        Objects.equals(this.name, classifiedPackageConfig.name) &&
        Objects.equals(this.promotions, classifiedPackageConfig.promotions) &&
        Objects.equals(this.publication, classifiedPackageConfig.publication) &&
        Objects.equals(this.type, classifiedPackageConfig.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(extensions, id, name, promotions, publication, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClassifiedPackageConfig {\n");
    sb.append("    extensions: ").append(toIndentedString(extensions)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    promotions: ").append(toIndentedString(promotions)).append("\n");
    sb.append("    publication: ").append(toIndentedString(publication)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

