/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * DeductionIncreaseOperationAllOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class DeductionIncreaseOperationAllOf {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type = "DEDUCTION_INCREASE";

  public static final String SERIALIZED_NAME_DEDUCTION = "deduction";
  @SerializedName(SERIALIZED_NAME_DEDUCTION)
  private Deduction deduction;


  public DeductionIncreaseOperationAllOf type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getType() {
    return type;
  }



  public void setType(String type) {
    this.type = type;
  }


  public DeductionIncreaseOperationAllOf deduction(Deduction deduction) {
    
    this.deduction = deduction;
    return this;
  }

   /**
   * Get deduction
   * @return deduction
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Deduction getDeduction() {
    return deduction;
  }



  public void setDeduction(Deduction deduction) {
    this.deduction = deduction;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeductionIncreaseOperationAllOf deductionIncreaseOperationAllOf = (DeductionIncreaseOperationAllOf) o;
    return Objects.equals(this.type, deductionIncreaseOperationAllOf.type) &&
        Objects.equals(this.deduction, deductionIncreaseOperationAllOf.deduction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, deduction);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeductionIncreaseOperationAllOf {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    deduction: ").append(toIndentedString(deduction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

