/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * GetSaleProductsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class GetSaleProductsResponse {
  public static final String SERIALIZED_NAME_PRODUCTS = "products";
  @SerializedName(SERIALIZED_NAME_PRODUCTS)
  private List<SaleProductResponseDto> products = new ArrayList<SaleProductResponseDto>();

  public static final String SERIALIZED_NAME_CATEGORIES = "categories";
  @SerializedName(SERIALIZED_NAME_CATEGORIES)
  private List<SaleProductResponseCategoriesDto> categories = null;

  public static final String SERIALIZED_NAME_FILTERS = "filters";
  @SerializedName(SERIALIZED_NAME_FILTERS)
  private List<ListingResponseFilters> filters = null;

  public static final String SERIALIZED_NAME_NEXT_PAGE = "nextPage";
  @SerializedName(SERIALIZED_NAME_NEXT_PAGE)
  private GetSaleProductsResponseNextPage nextPage;


  public GetSaleProductsResponse products(List<SaleProductResponseDto> products) {
    
    this.products = products;
    return this;
  }

  public GetSaleProductsResponse addProductsItem(SaleProductResponseDto productsItem) {
    this.products.add(productsItem);
    return this;
  }

   /**
   * Get products
   * @return products
  **/
  @ApiModelProperty(required = true, value = "")

  public List<SaleProductResponseDto> getProducts() {
    return products;
  }



  public void setProducts(List<SaleProductResponseDto> products) {
    this.products = products;
  }


  public GetSaleProductsResponse categories(List<SaleProductResponseCategoriesDto> categories) {
    
    this.categories = categories;
    return this;
  }

  public GetSaleProductsResponse addCategoriesItem(SaleProductResponseCategoriesDto categoriesItem) {
    if (this.categories == null) {
      this.categories = new ArrayList<SaleProductResponseCategoriesDto>();
    }
    this.categories.add(categoriesItem);
    return this;
  }

   /**
   * Get categories
   * @return categories
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<SaleProductResponseCategoriesDto> getCategories() {
    return categories;
  }



  public void setCategories(List<SaleProductResponseCategoriesDto> categories) {
    this.categories = categories;
  }


  public GetSaleProductsResponse filters(List<ListingResponseFilters> filters) {
    
    this.filters = filters;
    return this;
  }

  public GetSaleProductsResponse addFiltersItem(ListingResponseFilters filtersItem) {
    if (this.filters == null) {
      this.filters = new ArrayList<ListingResponseFilters>();
    }
    this.filters.add(filtersItem);
    return this;
  }

   /**
   * Get filters
   * @return filters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ListingResponseFilters> getFilters() {
    return filters;
  }



  public void setFilters(List<ListingResponseFilters> filters) {
    this.filters = filters;
  }


  public GetSaleProductsResponse nextPage(GetSaleProductsResponseNextPage nextPage) {
    
    this.nextPage = nextPage;
    return this;
  }

   /**
   * Get nextPage
   * @return nextPage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GetSaleProductsResponseNextPage getNextPage() {
    return nextPage;
  }



  public void setNextPage(GetSaleProductsResponseNextPage nextPage) {
    this.nextPage = nextPage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetSaleProductsResponse getSaleProductsResponse = (GetSaleProductsResponse) o;
    return Objects.equals(this.products, getSaleProductsResponse.products) &&
        Objects.equals(this.categories, getSaleProductsResponse.categories) &&
        Objects.equals(this.filters, getSaleProductsResponse.filters) &&
        Objects.equals(this.nextPage, getSaleProductsResponse.nextPage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(products, categories, filters, nextPage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetSaleProductsResponse {\n");
    sb.append("    products: ").append(toIndentedString(products)).append("\n");
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    nextPage: ").append(toIndentedString(nextPage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

