/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * The offer&#39;s statistics.
 */
@ApiModel(description = "The offer's statistics.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class OfferListingDtoV1Stats {
  public static final String SERIALIZED_NAME_WATCHERS_COUNT = "watchersCount";
  @SerializedName(SERIALIZED_NAME_WATCHERS_COUNT)
  private Integer watchersCount;

  public static final String SERIALIZED_NAME_VISITS_COUNT = "visitsCount";
  @SerializedName(SERIALIZED_NAME_VISITS_COUNT)
  private Integer visitsCount;


  public OfferListingDtoV1Stats watchersCount(Integer watchersCount) {
    
    this.watchersCount = watchersCount;
    return this;
  }

   /**
   * The number of users who added this offer to their watch lists.
   * @return watchersCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "99", value = "The number of users who added this offer to their watch lists.")

  public Integer getWatchersCount() {
    return watchersCount;
  }



  public void setWatchersCount(Integer watchersCount) {
    this.watchersCount = watchersCount;
  }


  public OfferListingDtoV1Stats visitsCount(Integer visitsCount) {
    
    this.visitsCount = visitsCount;
    return this;
  }

   /**
   * The number of unique users viewing this offer in the past 30 days.
   * @return visitsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of unique users viewing this offer in the past 30 days.")

  public Integer getVisitsCount() {
    return visitsCount;
  }



  public void setVisitsCount(Integer visitsCount) {
    this.visitsCount = visitsCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OfferListingDtoV1Stats offerListingDtoV1Stats = (OfferListingDtoV1Stats) o;
    return Objects.equals(this.watchersCount, offerListingDtoV1Stats.watchersCount) &&
        Objects.equals(this.visitsCount, offerListingDtoV1Stats.visitsCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(watchersCount, visitsCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OfferListingDtoV1Stats {\n");
    sb.append("    watchersCount: ").append(toIndentedString(watchersCount)).append("\n");
    sb.append("    visitsCount: ").append(toIndentedString(visitsCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

