/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Contains offers criteria
 */
@ApiModel(description = "Contains offers criteria")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class OfferCriterium {
  public static final String SERIALIZED_NAME_OFFERS = "offers";
  @SerializedName(SERIALIZED_NAME_OFFERS)
  private List<OfferId> offers = null;

  /**
   * Criteria type: CONTAINS_OFFERS
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    CONTAINS_OFFERS("CONTAINS_OFFERS");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;


  public OfferCriterium offers(List<OfferId> offers) {
    
    this.offers = offers;
    return this;
  }

  public OfferCriterium addOffersItem(OfferId offersItem) {
    if (this.offers == null) {
      this.offers = new ArrayList<OfferId>();
    }
    this.offers.add(offersItem);
    return this;
  }

   /**
   * Set of offers
   * @return offers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Set of offers")

  public List<OfferId> getOffers() {
    return offers;
  }



  public void setOffers(List<OfferId> offers) {
    this.offers = offers;
  }


  public OfferCriterium type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Criteria type: CONTAINS_OFFERS
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Criteria type: CONTAINS_OFFERS")

  public TypeEnum getType() {
    return type;
  }



  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OfferCriterium offerCriterium = (OfferCriterium) o;
    return Objects.equals(this.offers, offerCriterium.offers) &&
        Objects.equals(this.type, offerCriterium.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(offers, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OfferCriterium {\n");
    sb.append("    offers: ").append(toIndentedString(offers)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

