/*
 * Allegro REST API
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package allegro.application.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * QuoteResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-16T16:12:46.567+02:00[Europe/Belgrade]")
public class QuoteResponse {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_FEE = "fee";
  @SerializedName(SERIALIZED_NAME_FEE)
  private Price fee;

  public static final String SERIALIZED_NAME_CYCLE_DURATION = "cycleDuration";
  @SerializedName(SERIALIZED_NAME_CYCLE_DURATION)
  private String cycleDuration;

  public static final String SERIALIZED_NAME_CLASSIFIEDS_PACKAGE = "classifiedsPackage";
  @SerializedName(SERIALIZED_NAME_CLASSIFIEDS_PACKAGE)
  private ClassifiedPackage classifiedsPackage;


  public QuoteResponse name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Quote fee name.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Opłata za wystawienie.", value = "Quote fee name.")

  public String getName() {
    return name;
  }



  public void setName(String name) {
    this.name = name;
  }


  public QuoteResponse fee(Price fee) {
    
    this.fee = fee;
    return this;
  }

   /**
   * Get fee
   * @return fee
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Price getFee() {
    return fee;
  }



  public void setFee(Price fee) {
    this.fee = fee;
  }


  public QuoteResponse cycleDuration(String cycleDuration) {
    
    this.cycleDuration = cycleDuration;
    return this;
  }

   /**
   * Duration in ISO 8601 format.
   * @return cycleDuration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "PT240H", value = "Duration in ISO 8601 format.")

  public String getCycleDuration() {
    return cycleDuration;
  }



  public void setCycleDuration(String cycleDuration) {
    this.cycleDuration = cycleDuration;
  }


  public QuoteResponse classifiedsPackage(ClassifiedPackage classifiedsPackage) {
    
    this.classifiedsPackage = classifiedsPackage;
    return this;
  }

   /**
   * Get classifiedsPackage
   * @return classifiedsPackage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ClassifiedPackage getClassifiedsPackage() {
    return classifiedsPackage;
  }



  public void setClassifiedsPackage(ClassifiedPackage classifiedsPackage) {
    this.classifiedsPackage = classifiedsPackage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuoteResponse quoteResponse = (QuoteResponse) o;
    return Objects.equals(this.name, quoteResponse.name) &&
        Objects.equals(this.fee, quoteResponse.fee) &&
        Objects.equals(this.cycleDuration, quoteResponse.cycleDuration) &&
        Objects.equals(this.classifiedsPackage, quoteResponse.classifiedsPackage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, fee, cycleDuration, classifiedsPackage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuoteResponse {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    fee: ").append(toIndentedString(fee)).append("\n");
    sb.append("    cycleDuration: ").append(toIndentedString(cycleDuration)).append("\n");
    sb.append("    classifiedsPackage: ").append(toIndentedString(classifiedsPackage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

